# Gets URL and ENGLISH LABEL of all LandVoc concepts, ordered alphabetically by label.

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT * 
FROM <http://landvoc.landportal.info>
WHERE {
?concept a skos:Concept ;
  skos:prefLabel ?label .
  FILTER (lang(?label) = 'en')
}
ORDER BY ?label
