# Only in the graph http://datasets.landportal.info , the datasets has the skos:prefLabel 

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

CONSTRUCT {
   ?datasetURI a qb:DataSet ;
               a dcat:Dataset ;
               a skos:Concept ;
               skos:notation ?notationDataset ;
               dct:identifier ?notationDataset ;
               rdfs:label  ?label ;
               dct:title  ?label ;
               skos:prefLabel ?label ;
               rdfs:commnent ?description ;
               dct:description ?description ;
               rdfs:seeAlso ?datasetDrupalCurated ;
			   dct:publisher ?organizationURI .

   ?organizationURI a foaf:Organization ;
               skos:notation ?notationOrg;
               rdfs:label  ?labelOrg ;
               dct:title  ?labelOrg ;
               rdfs:seeAlso ?organizationDrupalCurated .
}
FROM <http://organizations.landportal.info>
FROM <http://datasets.landportal.info>
WHERE {
?datasetDrupal a qb:DataSet ;
         skos:notation ?notationDataset ;
         skos:prefLabel ?label ;
         skos:definition ?description ;
		 dct:publisher ?orgDrupal .

?orgDrupal foaf:name ?labelOrg ;
     dct:identifier ?notationOrg .

#VALUES ?notationDataset {"WB-ENV" "WB-CC"} .

BIND (IRI(CONCAT("http://data.landportal.info/dataset/",?notationDataset)) AS ?datasetURI)
BIND (IRI(REPLACE(REPLACE(STR(?datasetDrupal), "https://","http://"),"beta.landportal.info","landportal.info")) AS ?datasetDrupalCurated)

BIND (IRI(CONCAT("http://data.landportal.info/organization/",?notationOrg)) AS ?organizationURI)
BIND (IRI(REPLACE(REPLACE(STR(?orgDrupal), "https://","http://"),"beta.landportal.info","landportal.info")) AS ?organizationDrupalCurated)

} ORDER BY (?notationDataset)
