# Get number of observations by country (including the countries without any observation)
# Ordered by countryURI

PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX qb:   <http://purl.org/linked-data/cube#>

SELECT DISTINCT (STR(?iso3) as ?iso3) ?label (COUNT(?obs) AS ?nObs)
FROM <http://data.landportal.info>
FROM <http://countries.landportal.info>
WHERE{
   ?countryURI a <http://purl.org/weso/landbook/ontology#Country> ;
               rdfs:label ?label ;
               skos:notation ?iso3 .
   OPTIONAL{?obs cex:ref-area ?countryURI}
   FILTER isIRI(?countryURI)
} ORDER BY ?countryURI