# Get indicators that have, at least one value for a country.
# Returns indicatorURL and indicatorLabel
# Ordered by indicatorURL

PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX ex: <http://www.example.org/rdf#>

SELECT DISTINCT ?indicatorURL ?indicatorLabel ?indicatorDescription
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-indicator ?indicatorURL .
?indicatorURL ex:label ?indicatorLabel ;
              ex:description ?indicatorDescription .
} ORDER BY ?indicatorURL
