#!/usr/bin/python
# -*- coding: UTF-8 -*-

import json

def getUNM49code(label):
    return {
            'Africa': "002",
            'Americas': "019",
            'Asia': "142",
            'Caribbean': "029",
            'Central Africa': "017",
            'Central America': "013",
            'Central Asia': "143",
            'CIS (Commonwealth of Independent States)': [], #['ARM', 'BLR', 'KAZ', 'KGZ', 'MDA', 'RUS', 'TJK', 'TKM', 'UKR', 'UZB'], 
            'Eastern Africa': "014",
            'Eastern Asia': "030",
            'Eastern Europe': "151",
            'Europe': "150",
            'European Union Countries': [],#["AUT", "BEL", "BGR", "CYP", "CZE", "DEU", "DNK", "ESP", "EST", "FIN", "FRA", "GBR", "GRC", "HRV", "HUN", "IRL", "ITA", "LTU", "LUX", "LVA", "MLT", "NLD", "POL", "PRT", "ROU", "SVK", "SVN", "SWE"],
            'Landlocked Developing Countries': [],# ["AFG","ARM","AZE","BDI","BFA","BOL","BTN","BWA","CAF","ETH","KAZ","KGZ","LAO", "LSO","MDA","MKD","MLI","MNG","MWI","NER","NPL","PRY","RWA","SSD","SWZ","TCD","TJK","TKM","UGA","UZB","ZMB","ZWE"],
            'Least Developed Countries': None,
            'North America': "021",
            'North Asia': ['RUS'],
            'Northern Africa': "015",
            'Northern Europe': "154",
            'Oceania': "009",
            'Small Island Developing States': [], #["ABW", "AIA", "ASM", "ATG", "BHR", "BHS", "BLZ", "BRB", "COK", "COM", "CPV", "CUB", "CUW", "DMA", "DOM", "FJI", "FSM", "GNB", "GRD", "GUM", "GUY", "HTI", "JAM", "KIR", "KNA", "LCA", "MDV", "MHL", "MNP", "MSR", "NCL", "NIU", "NRU", "PLW", "PNG", "PRI", "PYF", "SGP", "SLB", "STP", "SUR", "SXM", "SYC", "TLS", "TON", "TTO", "TUV", "VCT", "VGB", "VIR", "VUT", "WSM"],
            'South America': "005",
            'South-Eastern Asia': "035",
            'Southern Africa': "018",
            'Southern Asia': "034",
            'Southern Europe': "039",
            'Western Africa': "011",
            'Western Asia': "145",
            'Middle East': "145",
            'Western Europe': "155",
    }[label]


def get_publisher(label):
    
    if "austlii.edu.au" in label:
        label = "www.austlii.edu.au"
        
    return {
        "www.legis-palop.org" : u"Projecto Apoio ao Desenvolvimento dos Sistemas Judiciários", 
        "www.qbz.gov.al" : u"Government of Albania", 
        "www.qpz.gov.al" : u"Government of Albania", 
        "www.bopa.ad" : u"Government of Andorra", 
        "www.laws.gov.ag" : u"Government of Antigua and Barbuda", 
        "www.ris.bka.gv.at" : u"Austrian Federal Government", 
        "www.e-qanun.az" : u"Government of Azerbaijan", 
        "http://www.presidence.gov.bi/" : u"Government of Burundi", 
        "www.assemblee.bi" : u"Government of Burundi", 
        "www.just.fgov.be" : u"Government of Belgium", 
        "www.droit-afrique" : u"Droit-Afrique", 
        "www.legiburkina.bf" : u"Government of Burkina Faso", 
        "bdlaws.minlaw.gov.bd" : u"Government of Bangladesh", 
        "www.parliament.bg" : u"Government of Bulgaria", 
        "www.legalaffairs.gov.bh" : u"Government of Bahrain", 
        "www.bahamas.gov.bs" : u"Government of the Bahamas",
        "laws.bahamas.gov.bs" : u"Government of the Bahamas",
        "www.skupstinabd.ba" : u"Government of Bosnia and Herzegovina", 
        "http://president.gov.by" : u"Government of Belarus", 
        "pravo.by" : u"Government of Belarus", 
        "www.bermudalaws.bm" : u"Government of Bermuda", 
        "www.planalto.gov.br" : u"Government of Brazil", 
        "www.senado.gov.br" : u"Government of Brazil", 
        "www.caricomlaw.org" : u"Legal Services of the Caribbean Community", 
        "www.agc.gov.bn" : u"Government of the Sultanate of Brunei Darussalam", 
        "www.nab.gov.bt" : u"Royal Government of Bhutan", 
        "www.laws.gov.bw" : u"Government of Botswana", 
        "www.gc.ca" : u"Government of Canada", 
        "www.admin.ch" : u"Government of Switzerland", 
        "www.gov.cn" : u"Government of the People's Republic of China",
        "www.chinaacc.com" : u"Government of the People's Republic of China",
        "www.chinalawedu.com" : u"Government of the People's Republic of China", 
        "www.leganet.cd" : u"Partenariat pour le développement social", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.imprenta.gov.co" : u"Government of Colombia", 
        "www.legis-palop.org" : u"Projecto Apoio ao Desenvolvimento dos Sistemas Judiciários", 
        "www.gaceta.go.cr" : u"Government of Costa Rica", 
        "www.imprentanacional.go.cr" : u"Government of Costa Rica", 
        "www.gacetaoficial.cu" : u"Government of Cuba", 
        "www.gaceteaoficial.cu" : u"Government of Cuba", 
        "www.gov.ky" : u"Government of the Cayman Islands", 
        "www.cylaw.org" : u"CyLaw", 
        "www.bgbl.de" : u"Government of Germany", 
        "www.retsinfo.dk" : u"Government of Denmark", 
        "www.retsinformation.dk" : u"Government of Denmark", 
        "www.suprema.gov.do" : u"Government of the Dominican Republic", 
        "www.joradp.dz" : u"Government of Algeria", 
        "www.registroficial.gob.ec" : u"Government of Ecuador", 
        "www.registroficial.gob.ecu" : u"Government of Ecuador", 
        "www.registroficial.gov.ec" : u"Government of Ecuador", 
        "www.tribunalconstitucional.gov.ec" : u"Government of Ecuador", 
        "www.boe.es" : u"Government of Spain", 
        "www.ethiopar.net" : u"Government of Ethiopia", 
        "www.finlex.fi" : u"FINLEX", 
        "www.fiji.gov.fj" : u"Government of Fiji", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.legifrance.gouv.fr" : u"Government of France", 
        "www.opsi.gov.uk" : u"Government of the United Kingdom", 
        "www.scotland-legislation.hmso.gov.uk" : u"Government of the United Kingdom", 
        "www.epa.gov.gh" : u"Environmental Protection Agency Ghana", 
        "www.nawasa.gd" : u"Grenada National Water & Sewerage Authority", 
        "www.guamcourts.org" : u"Government of Guam", 
        "www.guamlegislature.com" : u"Government of Guam", 
        "legalaffairs.gov.gy" : u"Government of Guyana", 
        "www.legalaffairs.gov.gy" : u"Government of Guyana", 
        "www.hah.hr" : u"Government of Croatia", 
        "www.nn.hr" : u"Government of Croatia", 
        "http://njt.hu/" : u"Government of Hungary", 
        "www.magyarorszag.hu" : u"Government of Hungary", 
        "http://www.indolaw.org/" : u"Government of Indonesia", 
        "www.downtoearth-indonesia.org" : u"Government of Indonesia", 
        "www.indolaw.org" : u"Government of Indonesia", 
        "india.gov.in" : u"Government of India", 
        "www.commonlii.org" : u"Government of India", 
        "www.india.gov.in" : u"Government of India", 
        "www.agriculture.gov.ie" : u"Government of Ireland", 
        "www.bailii.org" : u"British and Irish Legal Information Institute", 
        "www.bailli.org" : u"British and Irish Legal Information Institute", 
        "www.irishstatutebook.ie" : u"Government of Ireland", 
        "www.oireachtas.ie" : u"Government of Ireland", 
        "http://rc.majlis.ir/fa" : u"Government of Ireland", 
        "http://www.dastour.ir/" : u"Government of Ireland", 
        "www.japarliament.gov.jm" : u"Government of Jamaica", 
        "www.jerseylaw.je" : u"Jersey Legal Information Board", 
        "www.japaneselawtranslation.go.jp" : u"Government of Japan", 
        "http://adilet.zan.kz" : u"Government of the Republic of Kazakhstan", 
        "http://www.government.kz" : u"Government of the Republic of Kazakhstan", 
        "zher.kz" : u"Government of the Republic of Kazakhstan", 
        "kenyalaw.org" : u"Kenya Law", 
        "www.kenyalaw.org" : u"Kenya Law", 
        "http://cbd.minjust.gov.kg" : u"Government of Kyrgyzstan", 
        "www.minjust.gov.kg" : u"Government of Kyrgyzstan", 
        "www.klri.re.kr" : u"Government of South Korea", 
        "http://erml.moe.gov.lb" : u"Government of Lebanon", 
        "http://jo.pcm.gov.lb" : u"Government of Lebanon", 
        "www.moe.gov.lb" : u"Government of Lebanon", 
        "fornis.net" : u"Forestry Research Network of Sub-Saharan Africa", 
        "legislature.gov.lr" : u"Government of Republic of Liberia", 
        "www.fda.gov.lr" : u"Forestry Development Authority (FDA) - Republic of Liberia", 
        "www.gesetze.li" : u"Government of Liechtenstein", 
        "www.commonlii.org" : u"Commonwealth Legal Information Institute", 
        "www.documents.gov.lk" : u"Government of Sri Lanka", 
        "www.legilux.lu" : u"Government of Luxembourg", 
        "http://www.sgg.gov.ma/Législation/BulletinsOfficiels.aspx" : u"Government of Morocco", 
        "www.sgg.gov.ma" : u"Government of Morocco", 
        "http://www.cnlegis.gov.mg/" : u"Government of Madagascar", 
        "www.assemblee-nationale.mg" : u"Government of Madagascar", 
        "dof.gob.mx/" : u"Government of Mexico", 
        "www.vanuatu.usp.ac.fj" : u"University of the South Pacific", 
        "http://mali.eregulations.org" : u"Government of Mali", 
        "http://www.journal-officiel.ml/1/56/fr/journal-officiel/le-journal-officiel.html" : u"Government of Mali", 
        "http://www.sgg-mali.ml/JO/2016/mali-jo-2016-16.pdf" : u"Government of Mali", 
        "www.journal-officiel.ml/1/56/fr/journal-officiel/le-journal-officiel.html" : u"Government of Mali", 
        "www.sgg-mali.ml" : u"Government of Mali", 
        "www.doi.gov.mt" : u"Government of Malta", 
        "www.mrt.gov.me" : u"Government of Montenegro", 
        "www.cnmileg.gov.mp" : u"Government of the Northern Mariana Islands", 
        "www.legis-palop.org" : u"Projecto Apoio ao Desenvolvimento dos Sistemas Judiciários", 
        "http://www.rimgerddes.org/" : u"Groupe d'Etudes et de Recherches sur la Démocratie et le Développement Economique et Social en Mauritanie", 
        "agc.gov.ms" : u"Government of Montserrat", 
        "montserrat.worldlegislation.com" : u"Government of Montserrat", 
        "attorneygeneral.govmu.org" : u"Government of Mauritius", 
        "mauritiusassembly.govmu.org" : u"Government of Mauritius", 
        "supremecourt.intnet.mu" : u"Government of Mauritius",
        "www1.gov.mu"  : u"Government of Mauritius",
        "www.africanlawlibrary.net" : u"African Law Library", 
        "www.gov.mu" : u"Government of Mauritius", 
        "www.malawilii.org" : u"Malawi Legal Information Institute", 
        "www.cljlaw.com" : u"CLJ Legal Network Malaysia", 
        "www.lac.org.na" : u"Legal Assistance Center Namibia", 
        "www.parliament.gov.na" : u"Government of the Republic of Namibia", 
        "www.saflii.org" : u"South African Legal Information Institute", 
        "www.droit-afrique.com" : u"Droit-Afrique", 
        "www.aksgonline.com" : u"Government of Nigeria", 
        "www.oyohouseofassembly.org" : u"Government of Nigeria", 
        "www.placng.org" : u"Government of Nigeria", 
        "www.asamblea.gob.ni" : u"Government of Nicaragua", 
        "www.lagaceta.gob.ni" : u"Government of Nicaragua", 
        "www.vanuatu.usp.ac.fj" : u"University of the South Pacific", 
        "www.overheid.nl" : u"Government of the Netherlands", 
        "www.lovdata.no" : u"Government of Norway", 
        "www.moad.gov.np" : u"Government of Nepal", 
        "www.legislation.govt.nz" : u"Government of New Zealand", 
        "www.asamblea.gob.pa" : u"Government of Panama", 
        "www.gaceetaoficial.gob.pa" : u"Government of Panama", 
        "www.gacetaoficial.gob.pa" : u"Government of Panama", 
        "www.minjus.gob.pe" : u"Government of Peru", 
        "www.chanrobles.com" : u"Chan Robles", 
        "www.denr.gov.ph" : u"Government of Philippines", 
        "www.gov.ph" : u"Government of Philippines", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.pacli.org" : u"Pacific Islands Legal Information Institute", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.lexjuris.com" : u"Government of Puerto Rico", 
        "www.dre.pt" : u"Government of Portugal", 
        "dzr.nnov.ru" : u"Government of Russia", 
        "http://7law.info" : u"Government of Russia", 
        "http://admlip.ru" : u"Government of Russia", 
        "http://arhangelsklaw.ru" : u"Government of Russia", 
        "http://docipedia.ru" : u"Government of Russia", 
        "http://docs.cntd.ru" : u"Government of Russia", 
        "http://info-ecology.ru" : u"Government of Russia", 
        "http://irkut.info" : u"Government of Russia", 
        "http://kadastr61.ru" : u"Government of Russia", 
        "http://kchr-gov.ru" : u"Government of Russia", 
        "http://kungur.permarea.ru" : u"Government of Russia", 
        "http://law.tularegion.ru" : u"Government of Russia", 
        "http://law.ulgov.ru" : u"Government of Russia", 
        "http://lawsrf.ru" : u"Government of Russia", 
        "http://ojm.tatarstan.ru" : u"Government of Russia", 
        "http://old.bryanskobl.ru" : u"Government of Russia", 
        "http://oopt.aari.ru" : u"Government of Russia", 
        "http://ossetia.regnews.org" : u"Government of Russia", 
        "http://palatavo.ru" : u"Government of Russia", 
        "http://pravo.gov.ru" : u"Government of Russia", 
        "http://publication.pravo.gov.ru" : u"Government of Russia", 
        "http://regzakon.fpa.su" : u"Government of Russia", 
        "http://rz7.info" : u"Government of Russia", 
        "http://volgoduma.ru" : u"Government of Russia", 
        "http://vologdazakon.ru" : u"Government of Russia", 
        "http://www.donland.ru" : u"Government of Russia", 
        "http://www.ecosakh.ru" : u"Government of Russia", 
        "http://www.fpa.su" : u"Government of Russia", 
        "http://www.garant.ru" : u"Government of Russia", 
        "http://www.gosuslugi.ru" : u"Government of Russia", 
        "http://www.krskstate.ru" : u"Government of Russia", 
        "http://www.lawsrf.ru" : u"Government of Russia", 
        "http://www.mosoblreg.ru" : u"Government of Russia", 
        "http://www.pravoregiona20.ru" : u"Government of Russia", 
        "http://www.regionz.ru" : u"Government of Russia", 
        "http://www.rg.ru" : u"Government of Russia", 
        "http://www.smolensk-gov.ru" : u"Government of Russia", 
        "http://www.systema.ru" : u"Government of Russia", 
        "http://www.vrnoblduma.ru" : u"Government of Russia", 
        "http://www.yarregion.ru" : u"Government of Russia", 
        "http://www.zakonprost.ru" : u"Government of Russia", 
        "http://www.zspo.ru" : u"Government of Russia", 
        "http://yariks.info" : u"Government of Russia", 
        "http://zakon.krskstate.ru" : u"Government of Russia", 
        "https://admbrk.ru" : u"Government of Russia", 
        "https://rg.ru" : u"Government of Russia", 
        "law.optima.ru" : u"Government of Russia", 
        "nko.economy.gov.ru" : u"Government of Russia", 
        "pravitelstvo.kbr.ru" : u"Government of Russia", 
        "publication.pravo.gov.ru" : u"Government of Russia", 
        "www.49gov.ru" : u"Government of Russia", 
        "www.garant.ru" : u"Government of Russia", 
        "www.government.ru" : u"Government of Russia", 
        "www.law.optima.ru" : u"Government of Russia", 
        "www.lawrussia.ru" : u"Government of Russia", 
        "www.pgpalata.ru" : u"Government of Russia", 
        "www.region.kostroma.ru" : u"Government of Russia", 
        "www.rg.ru" : u"Government of Russia", 
        "www.saratovmer.ru" : u"Government of Russia", 
        "www.vcom.ru" : u"Government of Russia", 
        "www.jo.gouv.sn" : u"Government of Senegal", 
        "statutes.agc.gov.sg" : u"Government of Singapore", 
        "www.ascension-island.gov.ac" : u"Government of Saint Helena, Ascension and Tristan da Cunha", 
        "www.sainthelena.gov.sh" : u"Government of Saint Helena, Ascension and Tristan da Cunha", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.parliament.gov.sl" : u"Government of Sierra Leone", 
        "www.csj.gob.sv" : u"Government of El Salvador", 
        "www.parlament.gov.rs" : u"Government of Serbia", 
        "www.gurtong.net" : u"Gurtong Trust", 
        "www.zakonypreludi.sk" : u"Government of Slovakia", 
        "www.zbierka.sk" : u"Government of Slovakia", 
        "www.pisrs.si" : u"Government of Slovenia", 
        "www.sintmaartengov.org" : u"Government of Sint Maarten", 
        "www.constituteproject.org" : u"Constitute Project", 
        "http://legitchad.cefod-tchad.org/" : u"Government of Chad", 
        "http://www.legitogo.gouv.tg" : u"Government of Togo", 
        "www.legitogo.gouv.tg" : u"Government of Togo", 
        "web.krisdika.go.th" : u"Government of Thailand", 
        "www.thailaws.com" : u"Government of Thailand", 
        "http://infoabad.com" : u"Government of Turkmenistan", 
        "www.cis-legal-reform.org" : u"Government of Turkmenistan", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "rgd.legalaffairs.gov.tt" : u"Government of Trinidad and Tobago", 
        "www.legalaffairs.gov.tt" : u"Government of Trinidad and Tobago", 
        "www.ttparliament.org" : u"Government of Trinidad and Tobago", 
        "www.iort.gov.tn" : u"Government of Tunesia", 
        "www.rega.basbakanlik.gov.tr" : u"Government of Turkey", 
        "www.resmigazete.gov.tr" : u"Government of Turkey", 
        "www.tarim.gov.tr" : u"Government of Turkey", 
        "www.tkgm.gov.tr" : u"Government of Turkey", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.parliament.go.tz" : u"Government of Tanzania", 
        "www.ulii.org" : u"Uganda Legal Information Institute", 
        "http://zakon1.rada.gov.ua" : u"Government of Ukraine",
        "http://zakon.rada.gov.ua" : u"Government of Ukraine",
        "http://rada.gov.ua" : u"Government of Ukraine",
        "www.rada.kiev.ua" : u"Government of Ukraine", 
        "www.presidencia.gub.uy" : u"Government of Uruguay", 
        "legcounsel.house.gov" : u"Government of the United States of America", 
        "leginfo.legislature.ca.gov" : u"Government of the United States of America", 
        "uscode.house.gov" : u"Government of the United States of America", 
        "www.asambleanacional.gov.ve" : u"República Bolivariana de Venezuela", 
        "www.tsj.gov.ve" : u"República Bolivariana de Venezuela", 
        "mol.gov.vu" : u"Government of Vanuatu", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.vanuatu.usp.ac.fj" : u"Government of Vanuatu", 
        "www.paclii.org" : u"Pacific Islands Legal Information Institute", 
        "www.palemene.ws" : u"Government of Samoa", 
        "mangaung.co.za" : u"Government of South Africa", 
        "www.gov.za" : u"Government of South Africa", 
        "www.info.gov.za" : u"Government of South Africa", 
        "www.mangaung.co.za" : u"Government of South Africa", 
        "www.polity.org.za" : u"Government of South Africa", 
        "www.azmec.co.zm" : u"Association of Zambian Mineral Exploration Companies", 
        "www.mewd.gov.zm" : u"Government of Zambia", 
        "www.parliament.gov.zm" : u"Government of Zambia", 
        "www.zambialii.org" : u"Zambia LII", 
        "www.parlzim.gov.zw" : u"Government of Zimbabwe", 
        "http://lex.justice.md" : u"Government of Moldova",
        "http://energyunit.gov.vc": u"Government of Saint Vincent and the Grenadines",
        "http://filial-nic-mkur.tj": u"Government of Tajikistan",
        "http://lawbelarus.com": u"Government of Belarus",
        "http://pravo.by": u"Government of Belarus",
        "http://lex.uz": u"Government of Uzbekistan",
        "http://www.lex.uz": u"Government of Uzbekistan",
        "http://www.gutf.cm": u"Government of Cameroon",
        "http://zakon1.rada.gov.ua": u"Government of Ukrania",
        "http://zakon2.rada.gov.ua": u"Government of Ukrania",
        "http://zakon3.rada.gov.ua": u"Government of Ukrania",
        "http://zakon4.rada.gov.ua": u"Government of Ukrania",
        "http://zakon5.rada.gov.ua": u"Government of Ukrania",
        "www.elperuano.com.pe": u"Government of Peru",
        "www.likumi.lv": u"Goverment of Latvia",
        "www.riigiteataja.ee": u"Government of Estonia",
        "https://e-seimas.lrs.lt": u"Goverment of Latvia",
        "www.mlr.gov.cn": u"Government of the People's Republic of China",
        "nepa.gov.jm": u"Government of Jamaica",
        "https://www.pnp.ru": u"Government of Russia",
        "www.moew.government.bg": u"Government of Bulgaria",
        "www.qbz.gov.al; www.ligjet.org": u"Government of Albania",
        "www.vietnamlawmagazine.vn": u"Government of Vietnam",
        "www.zakonyprolidi.cz": u"Government of the Czech Republic",
        "www.podnikame.cz": u"Government of the Czech Republic",
        "moi.gov.tw": u"Government of Taiwan",
        "epa.gov.tw": u"Government of Taiwan",
        "www.regionz.ru": u"Government of Russia",
        "www.sgg.cg": u"Government of Congo",
        "www.economie.gouv.cg": u"Government of Congo",
        "www.zes.gouv.cg": u"Government of Congo",
        "https://sgg.gouv.bj/": u"Government of Benin",
        "www.matsne.gov.ge": u"Government of Georgia",
        "https://matsne.gov.ge": u"Government of Georgia",
        "www.narodnaskupstinars.net": u"Government of Bosnia and Herzegovina",
        "www.permisdeconstruire.bj": u"Government of Benin",
        "www.sierra-leone.org": u"Government of Sierra Leone",
        "http://yasunitransparente.ambiente.gob.ec/parque-nacional-yasuni": u"Government of Ecuador",
        "www.caymanlandinfo.ky": u"Government of the Cayman Islands",
        "www.dgct.gouv.ml": u"Government of Mali",
        "www.lagaceta.hn": u"Government of Honduras",
        "www.legislation.gov.uk" : u"Government of the United Kingdom",
        "www.comlaw.gov.au; www.legislation.gov.au": u"Government of Australia",
        "www.legislation.qld.gov.au": u"Government of Queensland (Australia)",
        "www.legislation.vic.gov.au": u"Government of Victoria (Australia)",
        "www.dms.dpc.vic.gov.au/": u"Government of Victoria (Australia)",
        "www.dms.dpc.vic.gov.au": u"Government of Victoria (Australia)",
        "http://www.legislation.vic.gov.au": u"Government of Victoria (Australia)",
        "www.thelaw.tas.gov.au": u"Government of Tasmania (Australia)",
        "www.legislation.tas.gov.au": u"Government of Tasmania (Australia)",
        "legislation.tas.gov.au": u"Government of Tasmania (Australia)",
        "https://www.legislation.tas.gov.au": u"Government of Tasmania (Australia)",
        "www.slp.wa.gov.au": u"Government of Western Australia (Australia)",
        "www.legislation.sa.gov.au": u"Government of South Australia (Australia)",
        "www.legislation.nsw.gov.au": u"Government of New South Wales (Australia)",
        "www.primature.gov.rw": u"Government of Rwanda",
        "www.canada.justice.gc.ca" : u"Government of Canada",
        "www.qp.gov.sk.ca": u"Government of Saskatchewan (Canada)",
        "www.qp.gov.bc.ca": u"Government of British Columbian (Canada)",
        "www.qp.gov.bc.ca.": u"Government of British Columbian (Canada)",
        "www.gov.mb.ca": u"Government of Manitoba (Canada)",
        "www.gov.mb.ca.": u"Government of Manitoba (Canada)",
        "www.gov.on.ca": u"Government of Ontario (Canada)",
        "www.gov.ab.ca": u"Government of Alberta (Canada)",
        "www.gov.ab.ca.": u"Government of Alberta (Canada)",
        "www.gov.nb.ca": u"Government of New Brunswick (Canada)",
        "www.gnb.ca": u"Government of New Brunswick (Canada)",
        "www.gouv.qc.ca": u"Government of Quebec (Canada)",
        "www.gov.yk.ca": u"Government of Yukon (Canada)",
        "www.gov.nt.ca": u"Government of Northwest Territories (Canada)",
        "www..gov.nt.ca": u"Government of Northwest Territories (Canada)",
        "www.gov.nf.ca": u"Government of Newfoundland and Labrador (Canada)",
        "www.gov.ns.ca": u"Government of Nova Scotia (Canada)",
        "www.gov.ns.ca.": u"Government of Nova Scotia (Canada)",
        "www.gov.pe.ca": u"Government of Prince Edward Island (Canada)",
        "www.gov.nu.ca": u"Government of Nunavut (Canada)",
        "www.ybrd.gov.cn": u"Government of the People's Republic of China",
        "www.austlii.edu.au" : u"Australasian Legal Information Institute",
        "www6.austlii.edu.au" : u"Australasian Legal Information Institute",
        "http://www6.austlii.edu.au" : u"Australasian Legal Information Institute",
        "www.bmj.de": u"Government of Germany",
        "www.infoleg.gov.ar": u"Government of Argentina",
        "www.legislation.tn": u"Government of Tunisia",
        "www.mepate.gov.mg": u"Government of Madagascar",
        "www.moj.gov.jm": u"Government of Jamaica",
        "www.presidence.gov.bi": u"Government of Burundi",
        "www.saij.gob.ar/": u"Government of Argentina",
        "www.sgg.gov.gn": u"Government of Guinea",
        "www.sluzbenilist.me": u"Government of Montenegro",
        "www.documents.clientearth.org; www.legigabon.com": u"Government of Gabon",
        "www.dominica.gov.dm": u"Government of Dominica",
        "fsmlaw.org": u"Government of Micronesia",
        "www.bankzakonov.com": u"Government of Belarus",
        "http://latvia.news-city.info": u"Government of Latvia",
        "www. opsi.gov.uk": u"Government of United Kingdom",
        "isip.sejm.gov.pl": u"Government of Poland",
        "www.lawinfochina.com": u"Government of the People's Republic of China",
        "http://www.minjust.gov.kg": u"Government of Kyrgyzstan",
        "www.tonga-law.to": u"Government of Tonga",
        "crownlaw.gov.to": u"Government of Tonga",
        "http://jewish.news-city.info": u"Government of Israel",
        "www.belizelaw.org": u"Government of Belize",
        "www.legislation.gov.au": u"Government of Australia",
        "www.elaws.gov.bw": u"Government of Botswana",
        "www.tuvalu-legislation.tv": u"Government of Tuvalu",
        "tuvalu-legislation.tv": u"Government of Tuvalu",
        "http://www.gouv.bj/textes": u"Government of Benin",
        "www.info.gov.nf": u"Government of Norfolk Island",
        "www.qpz.gov.al; www.ligjet.org": u"Government of Albania",
        "www.guernseylegalresources.gg": u"Government of Guernsey",
        "www.government.kz": u"Government of the Republic of Kazakhstan",
        "europa.eu": u"European Union",
        "www.asbar.org": u"American Samoa Bar Association",
        "www.sierralii.org": u"Sierra Leone Legal Information Institute",
        "www.seylii.org": u"Seychelles Legal Information Institute",
        "62.95.69.15":  u"Government of Sweden",
        "punjablaws.gov.pk": u"Government of Pakistan",
        "www.legal-malta.com": u"Government of Malta",
        "www.tciyellowpages.com": u"Government of Turks and Caicos Islands",
        "www.environment.tc": u"Government of Turks and Caicos Islands",
        "www.docs.md": u"Government of Moldova",
        "www.cont.md": u"Government of Moldova",
        "www.agravista.md": u"Government of Moldova",
        "www.parlament.md": u"Government of Moldova",
        "www.environment.gov.ls": u"Government of Lesotho",
        "bdlaws.gov.bd": u"Government of Bangladesh",
        "http://adilet.minjust.kz": u"Government of the Republic of Kazakhstan",
        "www.hklii.org": u"Hong Kong Legal Information Institute",
        "www.hklii.hk": u"Hong Kong Legal Information Institute",
        "www.government.kg": u"Government of Kyrgyzstan",
        "http://www.nature.kg": u"Government of Kyrgyzstan",
        "legislation.to": u"Government of Tonga",
        "www3.lrs.lt": u"Government of Lithuania",
        "www.tm.lt": u"Government of Lithuania",
        "http://www.presidence.dj/jo/journal.php": u"Government of Djibouti",
        "www.kuiptk.ba": u"Government of Bosnia and Herzegovina",
        "www.lawcommission.gov.np": u"Government of Nepal",
        "www.et.gr": u"Government of Greece",
        "www.bmeia.gv.at": u"Austrian Federal Government",
        "www.mmaa.gov.qa": u"Government of Qatar",
        "www.agc.gov.my": u"Government of Malaysia",
        "www.congreso.gob.gt": u"Government of Guatemala",
        "www.rgurs.org": u"Government of Bosnia and Herzegovina",
        "www.guamattorneygeneral.com": u"Government of Guam",
        "http://government.ru": u"Government of Russia",
        "http://law7.ru": u"Government of Russia",
        "www.normasbrasil.com.br": u"Government of Brazil",
        "http://lawru.info": u"Government of Russia",
        "www.fsc.gov.et": u"Government of Ethiopia",
        "www.leyes.com.py": u"Government of Paraguay",
        "www.comores-droit.com": u"Government of Comoros",
        "http://www.parliament.am": u"Government of Armenia",
        "environment.gov.mu": u"Government of Mauritius",
        "www.diramb.gov.pt": u"Governo de Portugal",
        "www.lei.adv.br": u"Government of Brazil",
        "www.iucn.org": u"International Union for Conservation of Nature",
        "www.lawbelarus.com": u"Government of Belarus",
        "www.leychile.cl": u"Government of Chile",
        "www.jocomores.gouv.km": u"Government of Comoros",
        "www.lex.uz": u"Government of Uzbekistan",
        "http://www.legalaffairs.gov.bh": u"Government of Bahrain",
        "www.government.pn": u"Government of Pitcairn Islands",
        "http://www.pravo.by": u"Government of Belarus",
        "www.pravo.by": u"Government of Belarus",
        "http://pravoby.info": u"Government of Belarus",
        "www.caricom.org": u"Legal Services of the Caribbean Community"

    }.get(label, label)

def getLLR_types(label):
    return {
        'C': ["Constitution"],
        'P': ["National Policies"],
        'L': ["Legislation"],
        'R': ["Regulations"],
        'A': ["International Conventions or Treaties"],
        'M': ["Other"]
    }[label]
