# Get the number of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT COUNT (DISTINCT ?llr)
FROM <http://library.landportal.info>
WHERE {
    ?llr a bibo:Document .
}


# Get the number of distinct publishers of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT COUNT (DISTINCT ?publisher)
FROM <http://library.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher
}

# Get the list of URI and names of distinct publishers of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT DISTINCT ?publisher ?publisherName
FROM <http://library.landportal.info>
FROM <http://organizations.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher .
	?publisher schema:name ?publisherName .
}
ORDER BY ?publisherName


# Get the list of URI, names of distinct publishers of LLRs AND the number of LLRs of each publisher in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT DISTINCT ?publisher ?publisherName COUNT (?llr) as ?numberOfLLRs
FROM <http://library.landportal.info>
FROM <http://organizations.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher .
	?publisher schema:name ?publisherName .
}
ORDER BY ?publisherName
