# Get the number of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT COUNT (DISTINCT ?llr)
FROM <http://library.landportal.info>
WHERE {
    ?llr a bibo:Document .
}

# Get the number of LLRs by country/region
PREFIX bibo:<http://purl.org/ontology/bibo/>
SELECT ?region_title  (COUNT(?llr) AS ?no_llr)
FROM <http://library.landportal.info>
FROM <http://regions.landportal.info>
WHERE {
    ?llr a bibo:Document ;
     dct:spatial ?area .
?area dct:title ?region_title .
}

GROUP BY ?region_title
ORDER BY ?region_title



# Get the number of distinct publishers of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT COUNT (DISTINCT ?publisher)
FROM <http://library.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher
}

# Get the list of URI and names of distinct publishers of LLRs in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT DISTINCT ?publisher ?publisherName
FROM <http://library.landportal.info>
FROM <http://organizations.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher .
	?publisher schema:name ?publisherName .
}
ORDER BY ?publisherName


# Get the list of URI, names of distinct publishers of LLRs AND the number of LLRs of each publisher in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT DISTINCT ?publisher ?publisherName COUNT (?llr) as ?numberOfLLRs
FROM <http://library.landportal.info>
FROM <http://organizations.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher .
	?publisher schema:name ?publisherName .
}
ORDER BY ?publisherName

# Get the list of URI, names of distinct publishers of LLRs, the type of organization AND the number of LLRs of each publisher in the LOD
PREFIX bibo:<http://purl.org/ontology/bibo/>
PREFIX schema:<http://schema.org/>
SELECT DISTINCT ?publisher ?publisherName ?organizationType COUNT (?llr) as ?numberOfLLRs
FROM <http://library.landportal.info>
FROM <http://organizations.landportal.info>
FROM <http://organization-types.landportal.info>
WHERE {
    ?llr a bibo:Document ;
        schema:publisher ?publisher .
	?publisher schema:name ?publisherName .
    ?publisher dct:type ?organizationTypeURI .
    ?organizationTypeURI rdfs:label ?organizationType .
}
ORDER BY ?publisherName
