PREFIX ex:<http://example.org/>
SELECT ?indicator (MIN(?value) as ?minValue) (MAX(?value) as ?maxValue) 
FROM <http://min-max.landportal.info> 
WHERE{ 
?obs ex:indicator ?indicator; 
     ex:value ?value .
}