#!/usr/bin/python
# -*- coding: UTF-8 -*-
def getUNM49code(label):
    return {
            'Africa': "002",
            'Americas': "019",
            'Asia': "142",
            'Caribbean': "029",
            'Central Africa': "017",
            'Central America': "013",
            'Central Asia': "143",
            'CIS (Commonwealth of Independent States)': None,
            'Eastern Africa': "014",
            'Eastern Asia': "030",
            'Eastern Europe': "151",
            'Europe': "150",
            'European Union Countries': None,
            'Landlocked Developing Countries': None,
            'Least Developed Countries': None,
            'North America': "021",
            'North Asia': None,
            'Northern Africa': "015",
            'Northern Europe': "154",
            'Oceania': "009",
            'Small Island Developing States': None,
            'South America': "005",
            'South-Eastern Asia': "035",
            'Southern Africa': "018",
            'Southern Asia': "034",
            'Southern Europe': "039",
            'Western Africa': "011",
            'Western Asia': "145",
            'Western Europe': "155",
            'Northern America': "021",
            'World': "001",
            'Australia and New Zealand': "053",
            'Australia And New Zealand': "053",
    }[label]

def getISO3166_1_alpha3_code(label):
    return {
        "Aruba" : "ABW", 
        "Afghanistan" : "AFG", 
        "Angola" : "AGO", 
        "Anguilla" : "AIA", 
        "Åland Islands" : "ALA", 
        "Albania" : "ALB", 
        "Andorra" : "AND", 
        "United Arab Emirates" : "ARE", 
        "Argentina" : "ARG", 
        "Armenia" : "ARM", 
        "American Samoa" : "ASM", 
        "Antarctica" : "ATA", 
        "French Southern Territories" : "ATF", 
        "Antigua and Barbuda" : "ATG", 
        "Australia" : "AUS", 
        "Austria" : "AUT", 
        "Azerbaijan" : "AZE", 
        "Burundi" : "BDI", 
        "Belgium" : "BEL", 
        "Benin" : "BEN", 
        "Bonaire, Sint Eustatius and Saba" : "BES", 
        "Burkina Faso" : "BFA", 
        "Bangladesh" : "BGD", 
        "Bulgaria" : "BGR", 
        "Bahrain" : "BHR", 
        "Bahamas" : "BHS", 
        "Bosnia and Herzegovina" : "BIH", 
        "Saint Barthélemy" : "BLM", 
        "Belarus" : "BLR", 
        "Belize" : "BLZ", 
        "Bermuda" : "BMU", 
        "Bolivia, Plurinational State of" : "BOL", 
        "Brazil" : "BRA", 
        "Barbados" : "BRB", 
        "Brunei Darussalam" : "BRN", 
        "Bhutan" : "BTN", 
        "Bouvet Island" : "BVT", 
        "Botswana" : "BWA", 
        "Central African Republic" : "CAF", 
        "Canada" : "CAN", 
        "Cocos (Keeling) Islands" : "CCK", 
        "Switzerland" : "CHE", 
        "Chile" : "CHL", 
        "China" : "CHN", 
        u"Côte d'Ivoire" : "CIV", 
        "Cameroon" : "CMR", 
        "Congo, The Democratic Republic of the" : "COD", 
        "Congo" : "COG", 
        "Cook Islands" : "COK", 
        "Colombia" : "COL", 
        "Comoros" : "COM", 
        "Cabo Verde" : "CPV",
        "Cape Verde" : "CPV",
        "Costa Rica" : "CRI", 
        "Cuba" : "CUB", 
        "Curaçao" : "CUW", 
        "Christmas Island" : "CXR", 
        "Cayman Islands" : "CYM", 
        "Cyprus" : "CYP", 
        "Czechia" : "CZE", 
        "Germany" : "DEU", 
        "Djibouti" : "DJI", 
        "Dominica" : "DMA", 
        "Denmark" : "DNK", 
        "Dominican Republic" : "DOM", 
        "Algeria" : "DZA", 
        "Ecuador" : "ECU", 
        "Egypt" : "EGY", 
        "Eritrea" : "ERI", 
        "Western Sahara" : "ESH", 
        "Spain" : "ESP", 
        "Estonia" : "EST", 
        "Ethiopia" : "ETH", 
        "Finland" : "FIN", 
        "Fiji" : "FJI", 
        "Falkland Islands (Malvinas)" : "FLK", 
        "France" : "FRA", 
        "Faroe Islands" : "FRO", 
        "Micronesia, Federated States of" : "FSM", 
        "Gabon" : "GAB", 
        "United Kingdom" : "GBR", 
        "Georgia" : "GEO", 
        "Guernsey" : "GGY", 
        "Ghana" : "GHA", 
        "Gibraltar" : "GIB", 
        "Guinea" : "GIN", 
        "Guadeloupe" : "GLP", 
        "Gambia" : "GMB", 
        "Guinea-Bissau" : "GNB", 
        "Equatorial Guinea" : "GNQ", 
        "Greece" : "GRC", 
        "Grenada" : "GRD", 
        "Greenland" : "GRL", 
        "Guatemala" : "GTM", 
        "French Guiana" : "GUF", 
        "Guam" : "GUM", 
        "Guyana" : "GUY", 
        "Hong Kong" : "HKG", 
        "Heard Island and McDonald Islands" : "HMD", 
        "Honduras" : "HND", 
        "Croatia" : "HRV", 
        "Haiti" : "HTI", 
        "Hungary" : "HUN", 
        "Indonesia" : "IDN", 
        "Isle of Man" : "IMN", 
        "India" : "IND", 
        "British Indian Ocean Territory" : "IOT", 
        "Ireland" : "IRL", 
        "Iran, Islamic Republic of" : "IRN", 
        "Iraq" : "IRQ", 
        "Iceland" : "ISL", 
        "Israel" : "ISR", 
        "Italy" : "ITA", 
        "Jamaica" : "JAM", 
        "Jersey" : "JEY", 
        "Jordan" : "JOR", 
        "Japan" : "JPN", 
        "Kazakhstan" : "KAZ", 
        "Kenya" : "KEN", 
        "Kyrgyzstan" : "KGZ", 
        "Cambodia" : "KHM", 
        "Kiribati" : "KIR", 
        "Saint Kitts and Nevis" : "KNA", 
        "Korea, Republic of" : "KOR", 
        "Kuwait" : "KWT", 
        "Lao People's Democratic Republic" : "LAO", 
        "Lebanon" : "LBN", 
        "Liberia" : "LBR", 
        "Libya" : "LBY", 
        "Saint Lucia" : "LCA", 
        "Liechtenstein" : "LIE", 
        "Sri Lanka" : "LKA", 
        "Lesotho" : "LSO", 
        "Lithuania" : "LTU", 
        "Luxembourg" : "LUX", 
        "Latvia" : "LVA", 
        "Macao" : "MAC", 
        "Saint Martin (French part)" : "MAF", 
        "Morocco" : "MAR", 
        "Monaco" : "MCO", 
        "Moldova, Republic of" : "MDA", 
        "Madagascar" : "MDG", 
        "Maldives" : "MDV", 
        "Mexico" : "MEX", 
        "Marshall Islands" : "MHL", 
        "Macedonia, Republic of" : "MKD", 
        "Mali" : "MLI", 
        "Malta" : "MLT", 
        "Myanmar" : "MMR", 
        "Montenegro" : "MNE", 
        "Mongolia" : "MNG", 
        "Northern Mariana Islands" : "MNP", 
        "Mozambique" : "MOZ", 
        "Mauritania" : "MRT", 
        "Montserrat" : "MSR", 
        "Martinique" : "MTQ", 
        "Mauritius" : "MUS", 
        "Malawi" : "MWI", 
        "Malaysia" : "MYS", 
        "Mayotte" : "MYT", 
        "Namibia" : "NAM", 
        "New Caledonia" : "NCL", 
        "Niger" : "NER", 
        "Norfolk Island" : "NFK", 
        "Nigeria" : "NGA", 
        "Nicaragua" : "NIC", 
        "Niue" : "NIU", 
        "Netherlands" : "NLD", 
        "Norway" : "NOR", 
        "Nepal" : "NPL", 
        "Nauru" : "NRU", 
        "New Zealand" : "NZL", 
        "Oman" : "OMN", 
        "Pakistan" : "PAK", 
        "Panama" : "PAN", 
        "Pitcairn" : "PCN", 
        "Peru" : "PER", 
        "Philippines" : "PHL", 
        "Palau" : "PLW", 
        "Papua New Guinea" : "PNG", 
        "Poland" : "POL", 
        "Puerto Rico" : "PRI", 
        "Korea, Democratic People's Republic of" : "PRK", 
        "Portugal" : "PRT", 
        "Paraguay" : "PRY", 
        "Palestine, State of" : "PSE", 
        "French Polynesia" : "PYF", 
        "Qatar" : "QAT", 
        "Réunion" : "REU", 
        "Romania" : "ROU", 
        "Russian Federation" : "RUS", 
        "Rwanda" : "RWA", 
        "Saudi Arabia" : "SAU", 
        "Sudan" : "SDN", 
        "Senegal" : "SEN", 
        "Singapore" : "SGP", 
        "South Georgia and the South Sandwich Islands" : "SGS", 
        "Saint Helena, Ascension and Tristan da Cunha" : "SHN", 
        "Svalbard and Jan Mayen" : "SJM", 
        "Solomon Islands" : "SLB", 
        "Sierra Leone" : "SLE", 
        "El Salvador" : "SLV", 
        "San Marino" : "SMR", 
        "Somalia" : "SOM", 
        "Saint Pierre and Miquelon" : "SPM", 
        "Serbia" : "SRB", 
        "South Sudan" : "SSD", 
        "Sao Tome and Principe" : "STP", 
        "Suriname" : "SUR", 
        "Slovakia" : "SVK", 
        "Slovenia" : "SVN", 
        "Sweden" : "SWE", 
        "Swaziland" : "SWZ", 
        "Sint Maarten (Dutch part)" : "SXM", 
        "Seychelles" : "SYC", 
        "Syrian Arab Republic" : "SYR", 
        "Turks and Caicos Islands" : "TCA", 
        "Chad" : "TCD", 
        "Togo" : "TGO", 
        "Thailand" : "THA", 
        "Tajikistan" : "TJK", 
        "Tokelau" : "TKL", 
        "Turkmenistan" : "TKM", 
        "Timor-Leste" : "TLS", 
        "Tonga" : "TON", 
        "Trinidad and Tobago" : "TTO", 
        "Tunisia" : "TUN", 
        "Turkey" : "TUR", 
        "Tuvalu" : "TUV", 
        "Taiwan, Province of China" : "TWN", 
        "Tanzania, United Republic of" : "TZA", 
        "Uganda" : "UGA", 
        "Ukraine" : "UKR", 
        "United States Minor Outlying Islands" : "UMI", 
        "Uruguay" : "URY", 
        "United States" : "USA", 
        "Uzbekistan" : "UZB", 
        "Holy See (Vatican City State)" : "VAT", 
        "Saint Vincent and the Grenadines" : "VCT", 
        "Venezuela, Bolivarian Republic of" : "VEN", 
        "Virgin Islands, British" : "VGB", 
        "Virgin Islands, U.S." : "VIR", 
        "Viet Nam" : "VNM", 
        "Vanuatu" : "VUT", 
        "Wallis and Futuna" : "WLF", 
        "Samoa" : "WSM", 
        "Yemen" : "YEM", 
        "South Africa" : "ZAF", 
        "Zambia" : "ZMB", 
        "Zimbabwe" : "ZWE",
        "Bolivia" : "BOL", 
        "Moldova" : "MDA", 
        "Taiwan" : "TWN", 
        "Tanzania" : "TZA", 
        "Venezuela" : "VEN", 
        "Vietnam" : "VNM",
        "Islamic Republic of Afghanistan" : "AFG", 
        "Republic of Angola" : "AGO", 
        "Republic of Albania" : "ALB", 
        "Principality of Andorra" : "AND", 
        "Argentine Republic" : "ARG", 
        "Republic of Armenia" : "ARM", 
        "Republic of Austria" : "AUT", 
        "Republic of Azerbaijan" : "AZE", 
        "Republic of Burundi" : "BDI", 
        "Kingdom of Belgium" : "BEL", 
        "Republic of Benin" : "BEN", 
        "Bonaire, Sint Eustatius and Saba" : "BES", 
        "People's Republic of Bangladesh" : "BGD", 
        "Republic of Bulgaria" : "BGR", 
        "Kingdom of Bahrain" : "BHR", 
        "Commonwealth of the Bahamas" : "BHS", 
        "Republic of Bosnia and Herzegovina" : "BIH", 
        "Republic of Belarus" : "BLR", 
        "Plurinational State of Bolivia" : "BOL", 
        "Federative Republic of Brazil" : "BRA", 
        "Kingdom of Bhutan" : "BTN", 
        "Republic of Botswana" : "BWA", 
        "Swiss Confederation" : "CHE", 
        "Republic of Chile" : "CHL", 
        "People's Republic of China" : "CHN", 
        "Republic of Côte d'Ivoire" : "CIV", 
        "Republic of Cameroon" : "CMR", 
        "Republic of the Congo" : "COG", 
        "Republic of Colombia" : "COL", 
        "Union of the Comoros" : "COM", 
        "Republic of Cabo Verde" : "CPV", 
        "Republic of Costa Rica" : "CRI", 
        "Republic of Cuba" : "CUB", 
        "Curaçao" : "CUW", 
        "Republic of Cyprus" : "CYP", 
        "Czech Republic" : "CZE", 
        "Federal Republic of Germany" : "DEU", 
        "Republic of Djibouti" : "DJI", 
        "Commonwealth of Dominica" : "DMA", 
        "Kingdom of Denmark" : "DNK", 
        "People's Democratic Republic of Algeria" : "DZA", 
        "Republic of Ecuador" : "ECU", 
        "Arab Republic of Egypt" : "EGY", 
        "the State of Eritrea" : "ERI", 
        "Kingdom of Spain" : "ESP", 
        "Republic of Estonia" : "EST", 
        "Federal Democratic Republic of Ethiopia" : "ETH", 
        "Republic of Finland" : "FIN", 
        "Republic of Fiji" : "FJI", 
        "French Republic" : "FRA", 
        "Federated States of Micronesia" : "FSM", 
        "Gabonese Republic" : "GAB", 
        "United Kingdom of Great Britain and Northern Ireland" : "GBR", 
        "Republic of Ghana" : "GHA", 
        "Republic of Guinea" : "GIN", 
        "Islamic Republic of the Gambia" : "GMB", 
        "Republic of Guinea-Bissau" : "GNB", 
        "Republic of Equatorial Guinea" : "GNQ", 
        "Hellenic Republic" : "GRC", 
        "Republic of Guatemala" : "GTM", 
        "Republic of Guyana" : "GUY", 
        "Hong Kong Special Administrative Region of China" : "HKG", 
        "Republic of Honduras" : "HND", 
        "Republic of Croatia" : "HRV", 
        "Republic of Haiti" : "HTI", 
        "Hungary" : "HUN", 
        "Republic of Indonesia" : "IDN", 
        "Republic of India" : "IND", 
        "Islamic Republic of Iran" : "IRN", 
        "Republic of Iraq" : "IRQ", 
        "Republic of Iceland" : "ISL", 
        "State of Israel" : "ISR", 
        "Italian Republic" : "ITA", 
        "Hashemite Kingdom of Jordan" : "JOR", 
        "Republic of Kazakhstan" : "KAZ", 
        "Republic of Kenya" : "KEN", 
        "Kyrgyz Republic" : "KGZ", 
        "Kingdom of Cambodia" : "KHM", 
        "Republic of Kiribati" : "KIR", 
        "State of Kuwait" : "KWT", 
        "Lebanese Republic" : "LBN", 
        "Republic of Liberia" : "LBR", 
        "Libya" : "LBY", 
        "Principality of Liechtenstein" : "LIE", 
        "Democratic Socialist Republic of Sri Lanka" : "LKA", 
        "Kingdom of Lesotho" : "LSO", 
        "Republic of Lithuania" : "LTU", 
        "Grand Duchy of Luxembourg" : "LUX", 
        "Republic of Latvia" : "LVA", 
        "Macao Special Administrative Region of China" : "MAC", 
        "Kingdom of Morocco" : "MAR", 
        "Principality of Monaco" : "MCO", 
        "Republic of Moldova" : "MDA", 
        "Republic of Madagascar" : "MDG", 
        "Republic of Maldives" : "MDV", 
        "United Mexican States" : "MEX", 
        "Republic of the Marshall Islands" : "MHL", 
        "The Former Yugoslav Republic of Macedonia" : "MKD", 
        "Republic of Mali" : "MLI", 
        "Republic of Malta" : "MLT", 
        "Republic of Myanmar" : "MMR", 
        "Montenegro" : "MNE", 
        "Commonwealth of the Northern Mariana Islands" : "MNP", 
        "Republic of Mozambique" : "MOZ", 
        "Islamic Republic of Mauritania" : "MRT", 
        "Republic of Mauritius" : "MUS", 
        "Republic of Malawi" : "MWI", 
        "Republic of Namibia" : "NAM", 
        "Republic of the Niger" : "NER", 
        "Federal Republic of Nigeria" : "NGA", 
        "Republic of Nicaragua" : "NIC", 
        "Niue" : "NIU", 
        "Kingdom of the Netherlands" : "NLD", 
        "Kingdom of Norway" : "NOR", 
        "Federal Democratic Republic of Nepal" : "NPL", 
        "Republic of Nauru" : "NRU", 
        "Sultanate of Oman" : "OMN", 
        "Islamic Republic of Pakistan" : "PAK", 
        "Republic of Panama" : "PAN", 
        "Republic of Peru" : "PER", 
        "Republic of the Philippines" : "PHL", 
        "Republic of Palau" : "PLW", 
        "Independent State of Papua New Guinea" : "PNG", 
        "Republic of Poland" : "POL", 
        "Democratic People's Republic of Korea" : "PRK", 
        "Portuguese Republic" : "PRT", 
        "Republic of Paraguay" : "PRY", 
        "the State of Palestine" : "PSE", 
        "State of Qatar" : "QAT", 
        "Rwandese Republic" : "RWA", 
        "Kingdom of Saudi Arabia" : "SAU", 
        "Republic of the Sudan" : "SDN", 
        "Republic of Senegal" : "SEN", 
        "Republic of Singapore" : "SGP", 
        "Republic of Sierra Leone" : "SLE", 
        "Republic of El Salvador" : "SLV", 
        "Republic of San Marino" : "SMR", 
        "Federal Republic of Somalia" : "SOM", 
        "Republic of Serbia" : "SRB", 
        "Republic of South Sudan" : "SSD", 
        "Democratic Republic of Sao Tome and Principe" : "STP", 
        "Republic of Suriname" : "SUR", 
        "Slovak Republic" : "SVK", 
        "Republic of Slovenia" : "SVN", 
        "Kingdom of Sweden" : "SWE", 
        "Kingdom of Swaziland" : "SWZ", 
        "Sint Maarten (Dutch part)" : "SXM", 
        "Republic of Seychelles" : "SYC", 
        "Republic of Chad" : "TCD", 
        "Togolese Republic" : "TGO", 
        "Kingdom of Thailand" : "THA", 
        "Republic of Tajikistan" : "TJK", 
        "Democratic Republic of Timor-Leste" : "TLS", 
        "Kingdom of Tonga" : "TON", 
        "Republic of Trinidad and Tobago" : "TTO", 
        "Republic of Tunisia" : "TUN", 
        "Republic of Turkey" : "TUR", 
        "Taiwan, Province of China" : "TWN", 
        "United Republic of Tanzania" : "TZA", 
        "Republic of Uganda" : "UGA", 
        "Eastern Republic of Uruguay" : "URY", 
        "United States of America" : "USA", 
        "Republic of Uzbekistan" : "UZB", 
        "Bolivarian Republic of Venezuela" : "VEN", 
        "British Virgin Islands" : "VGB", 
        "Virgin Islands of the United States" : "VIR", 
        "Socialist Republic of Viet Nam" : "VNM", 
        "Republic of Vanuatu" : "VUT", 
        "Independent State of Samoa" : "WSM", 
        "Republic of Yemen" : "YEM", 
        "Republic of South Africa" : "ZAF", 
        "Republic of Zambia" : "ZMB", 
        "Republic of Zimbabwe" : "ZWE",
        "Bolivia (Plurinational State of)" : "BOL", 
        "Brunei" : "BRN",
        "Burkina" : "BFA",
        "Burma" : "MMR", 
        "Democratic Republic of Congo": "COD", 
        "Democratic Republic of the Congo": "COD",
        "East Timor": "TLS",
        "Holy See": "VAT",
        "Iran": "IRN",
        "Iran (Islamic Republic of)": "IRN",
        "Ivory Coast": "CIV",
        "Korea": "KOR",
        "Laos": "LAO",
        "Macedonia": "MKD",
        "Micronesia": "FSM",
        "Micronesia (Federated States of)": "FSM",
        "Republic of Korea": "KOR",
        "South Korea": "KOR",
        "Syria": "SYR",
        "The former Yugoslav Republic of Macedonia": "MKD",
        "Vatican City": "VAT",
        "Venezuela (Bolivarian Republic of)": "VEN",
            'Africa': "002",
            'Americas': "019",
            'Asia': "142",
            'Caribbean': "029",
            'Central Africa': "017",
            'Central America': "013",
            'Central Asia': "143",
            'CIS (Commonwealth of Independent States)': None,
            'Eastern Africa': "014",
            'Eastern Asia': "030",
            'Eastern Europe': "151",
            'Europe': "150",
            'European Union Countries': None,
            'Landlocked Developing Countries': None,
            'Least Developed Countries': None,
            'North America': "021",
            'North Asia': None,
            'Northern Africa': "015",
            'Northern Europe': "154",
            'Oceania': "009",
            'Small Island Developing States': None,
            'South America': "005",
            'South-Eastern Asia': "035",
            'Southern Africa': "018",
            'Southern Asia': "034",
            'Southern Europe': "039",
            'Western Africa': "011",
            'Western Asia': "145",
            'Western Europe': "155",
            'Northern America': "021",
            'World': "001",
            'Australia and New Zealand': "053",
            'Australia And New Zealand': "053",

    }[label]

def generate_authors(possible_authors):
    authors = set()
    for possible in possible_authors:
        if possible and unicode(possible).lower() !="fao":
            authors.add(possible)       
    return authors

def generate_organizations(possible_orgs):
    orgs = set()
    orgs.add(u"Food and Agriculture Organization of the United Nations (FAO)")
    for possible in possible_orgs:
        if not possible:
            continue 
        if possible in ["Regional Office for Africa", "Regional Office for the Near East", "Regional Office for Europe", "Regional Office for Latin America and the Caribbean", "Regional Office for Asia and the Pacific"]:
            orgs.add(possible)
        if possible in "Ministry of Agriculture and Cooperatives, Bangkok (Thailand)":
            orgs.add("Government of Thailand")
    return orgs
    
def get_types(source_type):
    return [{
        'Article' : 'Journal Articles & Books' ,
        'Book (series)' : 'Journal Articles & Books' ,
        'Book (stand-alone)' : 'Journal Articles & Books' ,
        'Book' : 'Journal Articles & Books' ,
        'Bulletin' : 'Policy Papers & Briefs' ,
        'Document' : 'Reports & Research',
        'Meeting' : 'Reports & Research', 
        'Mixed Material' : 'Policy Papers & Briefs',
        'Periodical' : 'Journal Articles & Books',
        'Project' : 'Policy Papers & Briefs',
        'Reports' : 'Reports & Research', 
        'Serials' : 'Journal Articles & Books',
        'Brochure (factsheet, flyer/leaflet, booklet)': 'Institutional & Promotional Materials',
        'Poster, banner' : 'Institutional & Promotional Materials',
        'Newsletter' : 'Institutional & Promotional Materials',
        'Journal, magazine, bulletin' : 'Policy Papers & Briefs',
        None: 'Other',
    }[source_type]]
