# Remove all metadata of an indicator
WITH <http://indicators.landportal.info> 
DELETE
{ ?indicator ?p ?o }
WHERE {
?indicator ?p ?o .
VALUES ?indicator {<http://data.landportal.info/indicator/VGGT.END.XXXX> } .
}

######

# Remove all metadata of indicators of a dataset

WITH <http://indicators.landportal.info> 
DELETE
{ ?indicator ?p ?o }
WHERE {
?indicator dct:source ?dataset ;
           ?p ?o .

VALUES ?dataset {<http://data.landportal.info/dataset/LS-XXXX>} .
}
