PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX ex: <http://www.example.org/rdf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?indicatorURL ?notation ?indicatorLabel ?indicatorDescription ?unitLabel ?datasetURI ?seeAlso
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-indicator ?indicatorURL .
OPTIONAL { ?indicatorURL skos:notation ?notation }
OPTIONAL { ?indicatorURL ex:label ?indicatorLabel }
OPTIONAL { ?indicatorURL ex:description ?indicatorDescription }
OPTIONAL { ?indicatorURL ex:unit ?unitLabel }
OPTIONAL { ?indicatorURL ex:dataset ?datasetURI }
OPTIONAL { ?indicatorURL rdfs:seeAlso ?seeAlso }
} ORDER BY ?notation


# NUMBER OF INDICATORS
PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX ex: <http://www.example.org/rdf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(*) AS ?count) {
SELECT DISTINCT ?indicatorURL ?notation ?indicatorLabel ?indicatorDescription ?unitLabel ?datasetURI ?seeAlso
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-indicator ?indicatorURL .
OPTIONAL { ?indicatorURL skos:notation ?notation }
OPTIONAL { ?indicatorURL ex:label ?indicatorLabel }
OPTIONAL { ?indicatorURL ex:description ?indicatorDescription }
OPTIONAL { ?indicatorURL ex:unit ?unitLabel }
OPTIONAL { ?indicatorURL ex:dataset ?datasetURI }
OPTIONAL { ?indicatorURL rdfs:seeAlso ?seeAlso }
} ORDER BY ?notation
}