PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX ex: <http://www.example.org/rdf#>

SELECT DISTINCT ?indicatorURL ?indicatorLabel ?indicatorDescription ?unitLabel ?datasetURL ?datasetLabel ?sourceOrgURL ?sourceOrgLabel
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-indicator ?indicatorURL .
OPTIONAL { ?indicatorURL ex:label ?indicatorLabel ;
              ex:description ?indicatorDescription ;
              ex:unit ?unitLabel ;
	      ex:dataset ?datasetURL .
			   
	 ?datasetURL ex:label ?datasetLabel ;
	             ex:org ?sourceOrgURL .
	
	 ?sourceOrgURL ex:label ?sourceOrgLabel.
	}
}