#!/usr/bin/python
# -*- coding: UTF-8 -*-

import sys

#Added from https://gist.github.com/onyxfish/322906#gistcomment-1701799
reload(sys)
sys.setdefaultencoding("utf-8")


def get_list_from_dd(dd):
    text_raw = str(dd).replace("<dd>","").replace("</dd>","")
    return [x.strip() for x in filter(None, text_raw.split("<br/>"))]
    

def get_concepts_from_vggt(voluntary_guidelines):
    
    project_concepts = set()
    
    #mapping voluntary_guidelines to chapters
    voluntary_guidelines_sections = voluntary_guidelines

# 2 General Matters
# 3AGeneral matters
# 3BPrinciples of implementation
# 4Rights and responsibilities
# 5Policy, legal and organizational frameworks
# 6Delivery of services
    voluntary_guidelines_sections = ["2" if x=="3A" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["2" if x=="3B" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["2" if x=="4" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["2" if x=="5" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["2" if x=="6" else x for x in voluntary_guidelines_sections]

# 3 Legal recognition and allocation of tenure rights
# 7Safeguards
# 8Public land, fisheries and forests
# 9Customary tenure systems
# 10Informal tenure            
    voluntary_guidelines_sections = ["3" if x=="7" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["3" if x=="8" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["3" if x=="9" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["3" if x=="10" else x for x in voluntary_guidelines_sections]

# 4 Transfers of tenure rights
# 11Markets
# 12Investments
# 13Land consolidation
# 14Restitution
# 15Redistributive reforms
# 16Expropriation and compensation

    voluntary_guidelines_sections = ["4" if x=="11" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["4" if x=="12" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["4" if x=="13" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["4" if x=="14" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["4" if x=="15" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["4" if x=="16" else x for x in voluntary_guidelines_sections]

# 5 Administration of tenure
# 17Records of tenure rights
# 18Valuation
# 19Taxation
# 20Spatial planning
# 21Dispute resolution
# 22Transboundary matters
    voluntary_guidelines_sections = ["5" if x=="17" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["5" if x=="18" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["5" if x=="19" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["5" if x=="20" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["5" if x=="21" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["5" if x=="22" else x for x in voluntary_guidelines_sections]

# 6 Responses to emergencies
# 23Climate change
# 24Natural disasters
# 25Conflicts in respect to tenure
    voluntary_guidelines_sections = ["6" if x=="23" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["6" if x=="24" else x for x in voluntary_guidelines_sections]
    voluntary_guidelines_sections = ["6" if x=="25" else x for x in voluntary_guidelines_sections]

# 7 Promotion, implementation, M & E
# 26Promotion, implementation, M & E
    voluntary_guidelines_sections = ["7" if x=="26" else x for x in voluntary_guidelines_sections]

    voluntary_guidelines_sections = set(voluntary_guidelines_sections)
    
    vggts_concepts_mapping_section = {"2" : ["land governance", "land law"],
                              "3" : ["land rights"],
                              "4" : ["land access", "land acquisitions", "land transfers"],
                              "5" : ["land administration", "land tenure systems", "security of tenure (land)"],
                              "6" : ["land governance"],
                              "7" : ["research", "land governance"]}
    
    vggts_concepts_mapping_item = { "3" : ["land governance", "land law"],
                                   "3A" : ["land governance", "land law"],
                                   "3B" : ["land governance", "land law"],
                                    "4" : ["land tenure", "land access", "land ownership"],
                                    "5" : ["land policies", "land governance", "land law"],
                                    "6" : ["land law", "legal empowerment"],
                                    "7" : ["indigenous peoples", "women", "indigenous land rights", "eviction"],
                                    "8" : ["state property", "public ownership", "fisheries", "forest land"],
                                    "9" : ["customary tenure", "customary law", "land tenure systems"],
                                   "10" : ["customary tenure", "customary law", "land tenure systems"],
                                   "11" : ["land markets"],
                                   "12" : ["land investments"],
                                   "13" : ["land consolidation"],
                                   "14" : ["compensation", "land allocation", "indigenous peoples"],
                                   "15" : ["land distribution", "land reform"],
                                   "16" : ["expropriation", "eminent domain", "compensation"],
                                   "17" : ["title deed", "land administration"],
                                   "18" : ["land valuation"],
                                   "19" : ["land markets"],
                                   "20" : ["land use planning"],
                                   "21" : ["land dispute", "land dispute resolution"],
                                   "22" : ["land dispute"],
                                   "23" : ["climate change"],
                                   "24" : ["natural disasters"],
                                   "25" : ["land conflicts"],
                                   "26" : ["research", "land governance"]}

    for section in voluntary_guidelines_sections:
        project_concepts.update(vggts_concepts_mapping_section[section])
    
    for item in voluntary_guidelines:
        project_concepts.update(vggts_concepts_mapping_item[item])
    
    project_concepts = set([unicode(x) for x in project_concepts])
    
    return project_concepts

def getOrganization_fromDonors(donors):
    return{
        "(NCIV) Netherlands Centre for Indigenous People": None,
        "Austria" : "Austrian Development Agency",
        "Belgium": "Belgian Development Agency",
        "Canada": "Global Affairs Canada",
        "Denmark": "Ministry of Foreign Affairs (Denmark)",
        "European Union": "European Union",
        "FAO": "Food and Agriculture Organization of the United Nations (FAO)",
        "Finland": "Ministry of Foreign Affairs (Finland)",
        "France": u"Agence Française de Développement",
        "Germany": "German Federal Ministry for Economic Cooperation and Development",
        "IFAD": "International Fund for Agricultural Development (IFAD)",
        "Japan": "Ministry of Foreign Affairs (Japan)",
        "Netherlands": "Ministry of Foreign Affairs of the Netherlands",
        "Norway": "Norwegian Agency for Development Cooperation",
        "Omidyar Network": "Omidyar Network",
        "Sweden" : "Swedish International Development Cooperation Agency (SIDA)",
        "Switzerland": "Swiss Agency for Development and Cooperation",
        "UN-Habitat": "United Nations Human Settlements Programme",
        "United Kingdom": "UK Department for International Development",
        "United States": "USAID",
        "World Bank": "World Bank Group"
    }.get(donors, None)

    


def getOrganization_fromImplementers(implementers):
    return{
        "(NCIV) Netherlands Centre for Indigenous People": ["Netherlands Centre for Indigenous Peoples"],
        "-\tGerman Development Cooperation \r\n-\tSwedish Bilateral Aid \r\n-\tFood and Agriculture Organisation": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "Swedish International Development Cooperation Agency (SIDA)", "Food and Agriculture Organization of the United Nations (FAO)"],
        "7.\tFoundation for ecological security": ["Foundation for Ecological Security"],
        "A coalition of 14 partners and 150 collaborator organizations": [],
        "AFF Secretariat": ["African Forest Forum"],
        "AGENCE FRANCAISE D'EXPERTISE TECHNIQUE INTERNATIONALE": ["Expertise France"],
        "Adam Smith International (ASI)": ["Adam Smith International"],
        "Adam Smith International, International Bank for Reconstruction and Development": ["Adam Smith International","International Bank for Reconstruction and Development"],
        "Addis Ababa University's Horn of Africa Regional Environment Centre &amp; Network (HoA-REC&amp;N)": ["Horn of Africa Regional Environment Centre and Network"],
        "African Land Policy Initiative (AU-UNECA-AfDB)": ["African Land Policy Centre"],
        "Agencia Peruana de Cooperaci\xc3\xb3n Internacional (DEVIDA)": ["Agencia Peruana de Cooperación Internacional"],
        "Agricultural Projects Implementation Unit of the Ministry of Agriculture Water Resources and Processing Industry Community Development and Investment Agency": ["Government of Kyrgyzstan"],
        "Agro Rural (of the Ministry of Agriculture)": ["Government of Peru"],
        "Amazon Conservation Team": ["Amazon Conservation Team"],
        "Amhara National Regional State Bureau of Finance and Economic Development": ["Ethiopia Regional State Government Amhara"],
        "Anthrowatch Corporation": ["Anthropology Watch"],
        "Asia Foundation": ["The Asia Foundation"],
        "Asia Indigenous Peoples Pact (AIPP)": ["Asia Indigenous Peoples Pact"],
        "Asociaci\xc3\xb3n de Forester\xc3\xada Comunitaria de Guatemala Ut\xe2\x80\x99z Che\xe2\x80\x99 Escuintla": [u"Asociación de Forestería Comunitaria de Guatemala Ut'z Che'"],
        "Associazione Italiana Agricoltura Biologica (AIAB)": [u"Associazione Italiana per l'Agricoltura Biologica"],
        "BTC": ["Belgian Development Agency"],
        "BTC (Belgian Technical Cooperation)": ["Belgian Development Agency"],
        "Bangladesh Water Development Board (Ministry of Water Resources)": ["Government of Bangladesh"],
        "British Council, Transparency International Bangladesh, World Bank": ["British Council", "Transparency International Bangladesh", "World Bank Group"],
        "British High Commission (Nigeria), World Bank, IBRD": ["British High Commission in Nigeria"],
        "Buhle Farmer\xe2\x80\x99 Academy (BFA), PTC+, Food Health Hope Foundation and others": [u"Buhle Farmers' Academy", "PTC+", "Food, Health and Hope Foundation"],
        "CAFOD, Caritas Lichinga": ["Catholic Agency For Overseas Development", "Caritas Mozambique"],
        "CALDH (local NGO)": [u"Centro para la Acción Legal en Derechos Humanos"],
        "CDE Bern, Land Core Group, Transnational Institute": ["Centre for Development and Environment", "Land Core Group", "Transnational Institute"],
        "CIAT, Expertise France, CSN, FIEF": ["Expertise France", "High Council of French Notariat"],
        "CICOL": ["Civil Society Coalition on Land"],
        "CIFOR": ["Center for International Forestry Research"],
        "CIFOR, FAO": ["Center for International Forestry Research", "Food and Agriculture Organization of the United Nations (FAO)"],
        "CIFOR, RECOTFC, ICRAF, NTFP-EP, SEARCA": ["Center for International Forestry Research", "The Center for People and Forests", "World Agroforestry Centre", "Non-Timber Forest Products - Exchange Programme", "Southeast Asian Regional Center for Graduate Study and Research in Agriculture"],
        "CIRAD": ["CIRAD"],
        "CIUF (Universit\xc3\xa9s francophones)": [u"Conseil Interuniversitaire de la Communauté Française de Belgique"],
        "CNVP Connecting Natural Values People": ["CNVP"],
        "COLANDEF": ["COLANDEF"],
        "Cadasta Foundation": ["Cadasta Foundation"],
        "Cape Institute for Agricultural Training (CIAT), Elsenburg College of Agriculture and University of Wageningen (WUR)": ["Elsenburg Agricultural Training Institute", "Wageningen University & Research"],
        "Cellule de la Planifcatione et de la Statistique du Secteur D\xc3\xa9veloppement Rural (CPS/SDR)": ["Government of Mali"],
        "Center for the Promotion of Agriculture": [u"Centro de Promoção da Agricultura"],
        "Centre for Public Policy (CPP) of the Indian Institute of Management Bangalore (IIMB)": ["Centre for Public Policy"],
        "Centro para la Autonom\xc3\xada y Desarrollo de los Pueblos Ind\xc3\xadgenas (CADPI)": [u"Centro para la Autonomía y Desarollo de los Pueblos Indígenas"],
        "Charity Projects (Comic Relief)": ["Comic Relief"],
        "Chemonics": ["Chemonics International"],
        "Chemonics International": ["Chemonics International"],
        "Christian Aid": ["Christian Aid"],
        "Cities Alliance": ["Cities Alliance"],
        "Civil Society Monitoring Commission - MC": ["Government of Colombia"],
        "Civil Society Organisations for Peace in Northern Uganda": ["Civil Society Organisations for Peace in Northern Uganda"],
        "Climate Technology Centre &amp; Network": ["Climate Technology Centre & Network"],
        "Cloudburst Consulting Group": ["Cloudburst Group"],
        "Coffey International Development, DAI Europe, Crown Agents, Government of Tanzania": ["Coffey", "DAI", "Crown Agents", "Government of Tanzania"],
        "Commissariat on Food Security": ["Government of Mali"],
        "Commission Nationale des Terres et AutresBiens": ["Commision Nationale des Terres et autres Biens (Burundi)"],
        "Community Self Reliance Center (CSRC).": ["Community Self Reliance Center"],
        "Conseil R\xc3\xa9gional de la R\xc3\xa9gion Boucle de Mouhoun": ["Government of Burkina Faso"],
        "Cooperativa de Terras Comunitarias": ["Iniciativa de Terras Comunitarias Foundation"],
        "Creditos Orbe": ["CrediOrbe"],
        "DAI": ["DAI"],
        "DIE": ["German Development Institute"],
        "DIE, GIGA, University of Zambia": ["German Development Institute", "German Institute of Global and Area Studies", "University of Zambia"],
        "Deloitte Consulting LLC": ["Deloitte"],
        "Democratic Governance Facility,(DGF)": ["Democratic Governance Facility"],
        "Department of Agriculture": ["Government of Philippines"],
        "Department of Forestry at the Ministry of Agriculture and Forestry, Lao PDR": ["Lao Ministry of Agriculture and Forestry","Government of Lao People's Democratic Republic"],
        "Department of Forests of the Ministry of Forests and Soil Conservation": ["Government of Nepal"],
        "Department of Irrigation, Ministry of Agriculture, Irrigation and Water Development": ["Government of Malawi"],
        "Department of State for Agriculture (DOSA)": ["Government of Gambia"],
        "Diakonia, SNV, Norwegian Church Aid, Helvetas Swiss Intercooperation": ["Diakonia", "SNV", "Norwegian Church Aid", "Helvetas"],
        "Dienst Landelijk Gebied (DLG), SNV, Macedonian Ministry for Agriculture, Forestry and Water Economy (MAFWE)": ["Ministry of Economic Affairs and Climate Policy of the Netherlands", "Government of the Republic of North Macedonia"],
        "Diligent Consulting": ["Diligent Consulting"],
        "Dinteg Org. Inc Corporation": ["Cordillera Indigenous Peoples Legal Center"],
        "Direction Nationale des Eaux et Forets (DNEF)/Forest Department of Mali": ["Government of Mali"],
        "ECORYS-led consortium of UK and Bangladesh organisations": ["Ecorys"],
        "END POVERTY": ["End Poverty"],
        "Environmental Justice Foundation (Coordinator International), Hen Mpoana (Ghanaian environmental NGO)": ["Environmental Justice Foundation", "Hen Mpoano"],
        "Eoropean Forest Institute": ["European Forest Institute"],
        "Ethio Wetlands and Natural Resource Association (EWNRA), WUR (NL), Huddersfield University (UK)": ["Ethio Wetlands and Natural Resources Association", "University of Huddersfield"],
        "Expertise France": ["Expertise France"],
        "FAO": ["Food and Agriculture Organization of the United Nations (FAO)"],
        "FAO (global through Multidonor Trust Fund) ; LPI Secretariat (Africa)": ["Food and Agriculture Organization of the United Nations (FAO)", "African Land Policy Centre"],
        "FAO (management) + Mozambiquan Centre for legal and judicial training (CFJJ) (implementation)": ["Food and Agriculture Organization of the United Nations (FAO)", "Center of Legal and Judicial Training"],
        "FAO + Mongolian Ministry of Nature and Environment": ["Government of Mongolia","Food and Agriculture Organization of the United Nations (FAO)"],
        "FAO and CIFOR": ["Food and Agriculture Organization of the United Nations (FAO)", "Center for International Forestry Research"],
        "FAO and WWF": ["Food and Agriculture Organization of the United Nations (FAO)","World Wildlife Fund"],
        "FAO, African Land Policy Centre (ALPC)": ["Food and Agriculture Organization of the United Nations (FAO)","African Land Policy Centre"],
        "FAO, IFAD": ["Food and Agriculture Organization of the United Nations (FAO)", "International Fund for Agricultural Development (IFAD)"],
        "FAO, National and International CSOs": ["Food and Agriculture Organization of the United Nations (FAO)"],
        "FAO, Transparancy International, KPMG, Oxford Policy Management, DAI Eurpe, Overseas Development Institute, IBRD, Columbia University, Cadasta Foundation, GIZ, Rights and Resources Institute, Namati, Landesa, Land Portal, Global Land Alliance": ["Food and Agriculture Organization of the United Nations (FAO)", "Transparency International", "KPMG", "Oxford Policy Management", "DAI", "Overseas Development Institute", "International Bank for Reconstruction and Development", "Columbia University", "Cadasta Foundation", u"Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "Rights and Resources Initiative", "Namati", "Landesa", "Land Portal Foundation", "Global Land Alliance"],
        "FAO, WRI, KPMG, IUCN Nederlands Comit\xc3\xa8, Internationakl Procurement Agency, FCO, Coffey International, Itad, Crown Agents, Palladium International, UN Forum on Forests, Global Witness, GIZ, Well Grounded, University of Wolverhampton, The European Timber Trade Federation, Rights and Resources Institute, Proforest, LTS International, International Institute for Environment and Development, Global Canopy, Forestry Commission of Ghana, Forest Trends, Forest Peoples Programme, Fern, European Forest Institute, Environmental Investigation Agency, ClientEarth, Chatham House, Centre for International Forestry Research": ["Food and Agriculture Organization of the United Nations (FAO)", "World Resources Institute", "KPMG", "International Union for Conservation of Nature", "International Procurement Agency", "Government of the United Kingdom", "Coffey", "ITAD", "Crown Agents", "Palladium", "United Nations Forum on Forests", "Global Witness", u"Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "Well Grounded", "University of Wolverhampton", "The European Timber Trade Federation", "Rights and Resources Initiative", "Proforest", "LTS International", "International Institute for Environment and Development", "Global Canopy", "The Forestry Commission of Ghana", "Forest Trends", "Forest Peoples Programme (FPP)", "Fern", "European Forest Institute", "Environmental Investigation Agency", "ClientEarth", "Chatham House", "Center for International Forestry Research"],
        "FIDA - IFAD": ["International Fund for Agricultural Development (IFAD)"],
        "Federal Ministry of Agriculture and Forestry": ["Government of Sudan"],
        "FinMark": ["FinMark Trust"],
        "Financial support to the FAO VGGT fiduciary fund": ["Food and Agriculture Organization of the United Nations (FAO)"],
        "Fondo Ecuatoriano-Canadiense de Desarrollo (FECD)": ["Fondo Ecuatoriano Canadiense de Desarrollo"],
        "Food Security Commissariat": ["Government of Mali"],
        "Forest Peoples Programme (FPP)": ["Forest Peoples Programme (FPP)"],
        "French MOFA, Adecia, CSN, FIEF": ["Government of France", "Agence Française de Développement", "High Council of French Notariat", "Expertise France"],
        "French Ministry of Foreign Affairs": ["Government of France"],
        "Friedrich-Naumann-Stiftung f\xc3\xbcr die Freiheit": ["Friedrich Naumann Foundation"],
        "Friends of the Nation, Oxfam GB, Environmental Justice Foundation, Hen Mpoano": ["Friends of the Nation", "Oxfam Great Britain", "Environmental Justice Foundation", "Hen Mpoano"],
        "Fundaci\xc3\xb3n Panamericana de Desarrollo, FUPAD": ["Fundación Panamericana de Desarrollo"],
        "GIZ": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH"],
        "GIZ and Agri Bank Namibia": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "Agri Bank Namibia"],
        "GIZ, Delegation of the European Union to the Republic of Niger": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "Delegation of the European Union to the Republic of Niger"],
        "GIZ, KfW": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH", "KFW"],
        "GIZ- German Society for International Cooperation": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH"],
        "GLTN": ["Global Land Tool Network"],
        "GLTN partners": ["Global Land Tool Network"],
        "GRAIN": ["GRAIN"],
        "GRET, E-Sud": ["Groupe de Recherches et d'Echanges Technologiques"],
        "Gesti\xc3\xb3n Centralizada": [],
        "GiZ": ["Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH"],
        "Global Land Tool Network (GLTN)": ["Global Land Tool Network"],
        "Government of Azad Jammu and Kashmir (AJK)": ["Government of Azad Jammu and Kashmir"],
        "Government of Colombia": ["Government of Colombia"],
        "Government of Ethiopia structures": ["Government of Ethiopia"],
        "Government of Grenada, Saint Lucia and Saint Vincent and the Grenadines; FAO": ["Government of Grenada", "Government of Saint Lucia", "Government of Saint Vincent and the Grenadines", "Food and Agriculture Organization of the United Nations (FAO)"],
        "Government of India, state governments of Meghalaya and Uttaranchal and respective rural development societies": ["Government of India "],
        "Government of Ivory Coast": ["Government of Ivory Coast"],
        "Government of Ivory Coast; ASSOCIATION INTERPROFESSIONNELLE DE LA FILIERE COTON (INTER COTON)": ["Government of Ivory Coast", "Association Interprofessionnelle de la Filiere Coton (INTERCOTON)"],
        "Government of Madhya Pradesh": ["Government of Madhya Pradesh"],
        "Government of Madhya Pradesh (GoMP) who are the lead, The Urban Administration and Development Department (UADD), a Municipal Strengthening Unit (MSU) established under the UADD. The Madhya Pradesh Urban Infrastructure Fund will be responsible for catalysing private sector resources.": ["Government of Madhya Pradesh", "Government of India"],
        "Government of Senegal- Ministry of Agriculture": ["Government of Senegal"],
        "Government of Tanzania, World Bank Group, Overseas Development Institute": ["Government of Tanzania", "World Bank Group", "Overseas Development Institute"],
        "Government of the Federal Republic of Brazil (SEAD - Secretaria Especial de Agricoltura Familiar e do Desenvolvimento Agrario)": ["Federal government of Brazil"],
        "Government of the Republic of Niger": ["Government of Niger"],
        "Guyana Lands and Surveys Commission (GLSC); FAO": ["Guyana Lands and Surveys Commission"],
        "HSS": ["Hanns Seidel Stiftung"],
        "Habitat for Humanity Brazil, Habitat for Humanity International": ["Habitat para Humanidade Brasil", "Habitat for Humanity International (HFHI)"],
        "Harakat": ["Harakat"],
        "Harewelle International, Cambridge Economic Policy Associates, Palladium International, LTS International, Crown Agents Bank, Ministry of Climate and Environment, Proforest": ["Harewelle International Limited", "Cambridge Economic Policy Associates", "Palladium", "LTS International", "Crown Agents Bank", "Government of Ghana", "Proforest"],
        "Helvetas Swiss Intercooperation": ["Helvetas Haiti"],
        "Hivos": ["Hivos"],
        "HoAREC": ["Horn of Africa Regional Environment Centre and Network"],
        "IASS, GRAF (Burkina Faso)": ["Institute for Advanced Sustainability Studies", u"Groupe de Recherche et d'Action sur le Foncier"],
        "IBI International": ["IBI"],
        "ICF": [],
        "ICMA": ["ICMA"],
        "IFAD": ["International Fund for Agricultural Development (IFAD)"],
        "IFAD/ILC": ["International Fund for Agricultural Development (IFAD)","International Land Coalition"],
        "ILC": ["International Land Coalition"],
        "ILC (IFAD)": ["International Land Coalition"],
        "INRA": ["Instituto Nacional de Reforma Agraria Bolivia"],
        "INRA + Kadaster": ["Instituto Nacional de Reforma Agraria Bolivia", "Kadaster International"],
        "IUCN": ["International Union for Conservation of Nature"],
        "IUCN Bangladesh, others": ["International Union for Conservation of Nature"],
        "IUCN PACO (Office for Central and West Africa), Ouagadougou": ["International Union for Conservation of Nature"],
        "IUCN, Council for Development of Social Science Research in Africa (CODESRIA), University of Illionis": ["International Union for Conservation of Nature", "Council for the Development of Social Science Research in Africa", "University of Illionis"],
        "Imbaraga": ["IMBARGA"],
        "Implementing: ITC, Polytechnic of Namibia, Catholic University of Mozambique/ Organization and management: ITC": ["Namibia University of Science and Technology", u"Universidade Católica de Moçambique", "Iniciativa de Terras Comunitarias Foundation"],
        "Indaba Agricultural Policy Research Institute (IAPRI)": ["Indaba Agricultural Policy Research Institute"],
        "Indian Institute for Human Settlements": ["Indian Institute for Human Settlements"],
        "Initiative Prospective Agricole et Rurale (IPAR)": ["Initiative Prospective Agricole et Rurale"],
        "Institute for Advanced Sustainability Studies (IASS)": ["Institute for Advanced Sustainability Studies"],
        "Institute for Development of Small-scale Fisheries (IDDPE)": [],
        "Institute for Poverty, Land and Agrarian Studies, University of Western Cape": ["Institute for Poverty, Land and Agrarian Studies"],
        "International Bank for Reconstruction and Development, New Partnership for Africa's Development,  International Partnership for African Fisheries Governance and Trade": ["International Bank for Reconstruction and Development", "New Partnership for Africa's Development"],
        "International Center for Research on Women": ["International Center for Research on Women"],
        "International Institute for Environment and Development (IIED)": ["International Institute for Environment and Development"],
        "International Institute for Environment and Development (IIEP), Centre pour l'environnement et le developpement (CED), Reseau de lutte contre la faim au Cameroun (RELUFA)": ["International Institute for Environment and Development", "Centre pour l'Environnement et le Développement Cameroun", "Reseau de lutte contre la faim au Cameroun"],
        "International Land Coalition": ["International Land Coalition"],
        "International Land Coalition (ILC)": ["International Land Coalition"],
        "International Monetary Fund (IFC) and the World Bank Group (WBG)": ["International Monetary Fund", "World Bank Group"],
        "JICA": ["Japan International Cooperation Agency"],
        "Japan International Cooperation Agency": ["Japan International Cooperation Agency"],
        "KAS, DR Congo: Conseil National des ONG pour le D\xc3\xa9veloppement (CNONGD), Sahel-Region: SOS Civisme, Centre Africa Obota": ["Konrad Adenauer Stiftung", u"Conseil National des ONG pour le Développement", "SOS Civisme", "Centre Africa Obota"],
        "KAS, Malawi: National Initiative for Civic Education (NICE), Farmers Union of Malawi (FUMU), National Association of Farmers in Malawi (NASFAM)\r\nNamibia: Women\xe2\x80\x99s Action for Development (WAD)\r\nZimbabwe: Self-Help Development Foundation (SHDF)\r\nBenin and Togo: Women in Law and Development\r\nBurkina Faso: Centre Africa Obota, SOS Civisme": ["Konrad Adenauer Stiftung", "National Initiative for Civic Education", "Farmers Union of Malawi", "National Association of Farmers in Malawi", "Women's Action for Development", "Self-Help Development Foundation", "Women in Law and Development in Africa", "SOS Civisme", "Centre Africa Obota"],
        "KPMG": ["KPMG"],
        "KPMG East Africa, Coffey International Development, DAI Europe, Crown Agents, Palladium International, AECOM, World Bank, Ministry of Finance and Economic Development (Ethiopia)": ["KPMG", "Coffey", "Crown Agents", "Palladium", "AECOM", "World Bank Group", "Ministry of Finance and Economic Development (Ethiopia)"],
        "KTH Royal Institute of Technology/The Swedish Mapping, Cadastral and Land Registration Authority": ["Royal Institute of Technology"],
        "Kadaster International": ["Kadaster International"],
        "Kadaster International and AREC": ["Kadaster International", "Agency for Real Estate Cadastre"],
        "KfW": ["KFW"],
        "Kindernothilfe": ["Kinder not hilfe"],
        "Kingdom of Swaziland": ["Government of Eswatini"],
        "LANDac Netherlands Academy for Land Governance": ["LANDac"],
        "LANDac Netherlands Academy on Land Governance": ["LANDac"],
        "LWF, AWF, ACC": ["The Lutheran World Federation", "Africa Wildlife Foundation", "African Conservation Centre"],
        "Land Equity International, GRET, GIZ": ["Land Equity International", "Groupe de Recherches et d'Echanges Technologiques", "Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH"],
        "Land Fund Manager hired from the private sector": [],
        "Land Matrix, LPI, FAO, Fondation Paul Ango Ela (FPAE), National Comity of rural Code in Niger, Enda Pronat and National Comission for the Land reform in Senegal": ["Land Matrix", "African Land Policy Centre", "Food and Agriculture Organization of the United Nations (FAO)", "Fondation Paul Ango Ela", "ENDA PRONAT"],
        "Land Policy Initiative Secretariat, IGAD Secretariat, UNECA": ["African Land Policy Centre", "Intergovernmental Authority on Development", "United Nations Economic Commission for Africa"],
        "Land Portal Foundation": ["Land Portal Foundation"],
        "Landesa": ["Landesa - Rural Development Institute"],
        "Lantm\xc3\xa4teriet": [u"Lantmäteriet"],
        "Legal Assistance for Rural Citizens": [],
        "Local Government Engineering Department (Ministry of Local Government Rural Development and Cooperatives)": ["Government of Bangladesh"],
        "Local farmer and producer organizations, SNV, KIT, Agriterra, LANDac": ["SNV", "Royal Tropical Institute", "Agriterra", "LANDac"],
        "MCA Benin": ["MCA Benin II"],
        "MGDPAAT (Adressing national committee), French Embassy in Cotonou": ["French Embassy in Cotonou"],
        "MIFUMI": ["MIFUMI"],
        "Manusher Jonno Foundation": ["Manusher Jonno Foundation"],
        "Meghalaya Basin Management Agency (MBMA)": ["Meghalaya Basin Management Agency"],
        "Meridia": [],
        "Michigan State University (MSU)": ["Michigan State University"],
        "Micro Aerial Projects LLC": ["Micro Aerial Projects LLC"],
        "Microbuild Fund": ["Microbuild Fund"],
        "Millennium Challenge Account - Burkina Faso": ["Millennium Challenge Account - Burkina Faso"],
        "Millennium Challenge Account - Cape Verde": ["Millennium Challenge Account - Cape Verde"],
        "Millennium Challenge Account - Indonesia": ["Millennium Challenge Account - Indonesia"],
        "Millennium Challenge Account - Lesotho; Land Administration Authority": ["Millennium Challenge Account - Lesotho"],
        "Millennium Challenge Account - Mongolia": ["Millennium Challenge Account - Mongolia"],
        "Millennium Challenge Account - Morocco": ["Millennium Challenge Account - Morocco"],
        "Millennium Challenge Account - Mozambique": ["Millennium Challenge Account - Mozambique"],
        "Millennium Challenge Account - Namibia": ["Millennium Challenge Account - Namibia"],
        "Millennium Challenge Account - Niger": ["Millennium Challenge Account - Niger"],
        "Millennium Challenge Account - Senegal": ["Millennium Challenge Account - Senegal"],
        "Minist\xc3\xa8re des Domaines de l'Etat et des Affaires Fonci\xc3\xa8res, French embassy in Mali": ["Government of Mali"],
        "Ministeries of decentralization, ministeries of economy and finance, local governments and French embassies in the 6 countries": ["Government of Mauritius"],
        "Ministre de l'Economie et des Finances": ["Government of Senegal"],
        "Ministry in charge of Water": ["Government of Chad"],
        "Ministry of Agrarian Affairs and Social Planning / National Land Agency - Indonesia": ["Government of Indonesia"],
        "Ministry of Agrarian Development (MDA), through the Secretariat of Territorial Development (SDT)": ["Government of Brazil","Ministério do Desenvolvimento Social e Agrário (Brazil)"],
        "Ministry of Agricultural Development": ["Government of Niger"],
"Ministry of Agriculture (Jordan)": ["Government of Jordan"],
"Ministry of Agriculture (Botswana)": ["Government of Botswana"],
"Ministry of Agriculture (Senegal)": ["Government of Senegal"],
"Ministry of Agriculture (Tunisia)": ["Government of Tunisia"],
"Ministry of Agriculture (Niger)": ["Government of Niger"],
"Ministry of Agriculture (Mali)": ["Government of Mali"],
"Ministry of Agriculture (Malawi)": ["Government of Malawi"],
"Ministry of Agriculture (Tajikistan)": ["Government of Tajikistan"],
"Ministry of Agriculture (Gambia, The)": ["Government of Gambia"],
"Ministry of Agriculture (Eritrea)": ["Government of Eritrea"],
"Ministry of Agriculture (Peru)": ["Government of Peru"],
"Ministry of Agriculture (Madagascar)": ["Government of Madagascar"],
"Ministry of Agriculture (El Salvador)": ["Government of El Salvador"],
"Ministry of Agriculture (Indonesia)": ["Government of Indonesia"],
"Ministry of Agriculture (Niger)": ["Government of Niger"],
"Ministry of Agriculture (Swaziland)": ["Government of Eswatini"],
"Ministry of Agriculture (Liberia)": ["Government of Liberia"],
"Ministry of Agriculture (Senegal)": ["Government of Senegal"],
"Ministry of Agriculture (Madagascar)": ["Government of Madagascar"],
        "Ministry of Agriculture (MOA)": ["Government of Tunisia"],
        "Ministry of Agriculture and Agrarian Reform (MAAR)": ["Government of Syrian Arab Republic"],
        "Ministry of Agriculture and Animal Resources": ["Government of Rwanda"],
        "Ministry of Agriculture and Breeding": ["Government of Guinea"],
        "Ministry of Agriculture and Cooperatives": ["Government of Zambia"],
        "Ministry of Agriculture and Food Security": ["Government of Lesotho"],
        "Ministry of Agriculture and Forestry": ["Lao Ministry of Agriculture and Forestry","Government of Lao People's Democratic Republic"],
        "Ministry of Agriculture and Irrigation": ["Government of Yemen"],
        "Ministry of Agriculture and Lands": ["Government of Zimbabwe"],
"Ministry of Agriculture and Livestock (Burundi)": ["Government of Burundi"],
"Ministry of Agriculture and Livestock (Niger)":["Government of Niger"],
        "Ministry of Agriculture and Livestock (MAG)": ["Government of El Salvador"],
        "Ministry of Agriculture and Maritime Fisheries": ["Government of Morocco"],
        "Ministry of Agriculture and Melioration": ["Government of Kyrgyzstan"],
        "Ministry of Agriculture and Ministry of Livestock": ["Government of Cameroon"],
        "Ministry of Agriculture and Ocean Fisheries": ["Government of Morocco"],
        "Ministry of Agriculture and Rural Development": ["Government of Colombia", "Ministerio de Agricultura y Desarrollo Rural (Colombia)"],
        "Ministry of Agriculture and Rural Development and the Amhara National Regional State": ["Government of Ethiopia","Ministry of Agriculture (Ethiopia)","Ethiopia Regional State Government Amhara"],
        "Ministry of Agriculture and Rural Development, National Rural Land Agency (AFOR)": ["Government of Ivory Coast"],
        "Ministry of Agriculture and Rural Development, the state governments of Amhara and Oromia Southern Nations, Peoples and Tigray": ["Government of Ethiopia"],
        "Ministry of Agriculture and Rural Infrastructure": ["Government of Senegal"],
"Ministry of Agriculture and Water Resources (Yemen)" : ["Government of Yemen"],
"Ministry of Agriculture and Water Resources (Tunisia)" : ["Government of Tunisia"],
"Ministry of Agriculture and Water Resources (Burkina Faso)" : ["Government of Burkina Faso"],
        "Ministry of Agriculture, Animal Industry and Fisheries": ["Government of Uganda"],
        "Ministry of Agriculture, Animal Wealth and Irrigation": ["Government of Sudan"],
        "Ministry of Agriculture, Federation of Chambers of Commerce and Industry": ["Government of Madagascar"],
        "Ministry of Agriculture, Fisheries and Rural Development": ["Government of Sao Tome and Principe"],
        "Ministry of Agriculture, Forestry and Fisheries": ["Government of the Kingdom of Cambodia"],
        "Ministry of Agriculture, Forestry and Food Security": ["Government of Sierra Leone"],
        "Ministry of Agriculture, Forestry and Food Security (Implementation support agency: FAO)": ["Government of Sierra Leone","Food and Agriculture Organization of the United Nations (FAO)"],
        "Ministry of Agriculture, Irrigation and Livestock (MAIL)": ["Government of the Islamic Republic of Afghanistan"],
        "Ministry of Agriculture, Livestock and Fisheries": ["Government of Madagascar"],
        "Ministry of Agriculture, Livestock and Nutrition (MAGA)": ["Government of Guatemala"],
        "Ministry of Agriculture, Livestock, Land and Irrigation": ["Government of Sri Lanka"],
        "Ministry of Agriculture, Natural Resources and Rural Development": ["Government of Haiti"],
        "Ministry of Agriculture, Rural Development and Marine Fisheries": ["Government of Morocco"],
        "Ministry of Agriculture, Water and Fisheries Resources": ["Government of Burkina Faso"],
        "Ministry of Agriculture, through the project coordination centre": ["Government of Georgia"],
        "Ministry of Environment": ["Government of Albania"],
        "Ministry of Environment and Sustainable Development (MEDD), Burkina Faso": ["Government of Burkina Faso"],
        "Ministry of Federal Affairs; Ministry of Agriculture and Rural Development; the National Regional State Governments of Afar, Oromia, Somali and the Southern Nations, Nationalities and Peoples Regional State; NGOs; and pastoral communities": ["Government of Somalia"],
"Ministry of Finance (Tanzania)" : ["Government of Tanzania"],
"Ministry of Finance (Guyana)" : ["Government of Guyana"],
"Ministry of Finance (Bangladesh)" : ["Government of Bangladesh"],
        "Ministry of Finance and National Economy": ["Government of Sudan"],
        "Ministry of Food, Agriculture and Light Industry": ["Government of Mongolia"],
        "Ministry of Housing Urban Poverty Alleviation (MoHUPA), Government of India (GoI)": ["Government of India"],
        "Ministry of Livestock and Fisheries Development": ["Government of Kenya"],
        "Ministry of Livestock and Fisheries Development (MLFD), Tanzania": ["Government of Tanzania"],
        "Ministry of Livestock, Fisheries and Rangelands": ["Government of Sudan"],
        "Ministry of Local Development": ["Government of Nepal"],
        "Ministry of Local Government, and district councils and local governments of 13 districts": ["Government of Uganda"],
        "Ministry of Planning (MINIPLAN)": ["Government of Burundi"],
        "Ministry of Planning and Investment": ["Government of Lao People's Democratic Republic"],
        "Ministry of Plantation Industries": ["Government of Sri Lanka"],
        "Ministry of Plantation Industry": ["Government of Sri Lanka"],
        "Ministry of Rural Development": ["Government of Mauritania"],
        "Ministry of Rural Development and Water (MDRE)": ["Government of Mali"],
        "Ministry of Tribal Affairs (MTA) and Scheduled Tribes and Scheduled Castes Development Department (ST/SCDD), Government of Orissa": ["Government of India", "Government of Odisha (India)"],
        "Ministry of Water and Irrigation": ["Government of Kenya"],
        "Ministry of Water and Livestock Development for the mainland and Ministry of Agriculture, Natural Resources, Environment and Cooperatives for Zanzibar": ["Government of Tanzania"],
        "Ministry of agriculture, farming and fishing (MAEP)": ["Government of Benin"],
        "Ministry of environment": ["Government of Ecuador"],
        "Mongolian Ministry of Nature and Environment": ["Government of Mongolia"],
        "NEW AMERICA": ["New America"],
        "NTFP-EP (Non-Timber Forest Products Exchange Programme)": ["Non-Timber Forest Products - Exchange Programme"],
        "National Center for State Courts (NCSC)": ["National Center for State Courts"],
        "National Cooperative Business Association (NCBA)": ["National Cooperative Business Association"],
        "National Cooperative Business Association\xe2\x80\x99s (NCBA) Cooperative League of the USA (CLUSA)": ["National Cooperative Business Association"],
        "National Directorate for Land and Forestry (DNTF), Ministry of Agriculture (MINAG)": ["Government of Mozambique"],
        "National Directorate for the Promotion of Rural Development": ["Government of Mozambique"],
        "National Forestry Commission (CONAFOR)": ["National Forestry Commission of Mexico"],
        "National Geographic Department": ["Government of Lao People's Democratic Republic"],
        "National Land Agency, Indonesia": ["Government of Indonesia"],
        "National University of Rwanda and ITC": ["National University of Rwanda"],
        "Natural Resources Institute (University of Greenwich), Stichting Aidenvironment": ["University of Greenwich - Natural Resources Institute", "Aidenvironment"],
        "Naturschutzbund Deutschland (NABU) e.V.": ["Naturschutzbund Deutschland"],
        "Netherlands Ministry of Foreign Affairs, Rabobank, ABN AMRO, ABP, APG, PGGM, ACTIAM, Pensioenfederatie, ING, FMO, AEGON, Nederlandse Vereniging van Banken, Coca Cola, Van Oord, LTO Nederland, Oxfam Novib, Both Ends, ActionAid, Tropenbos International, Milieudefensie, Hivos, Solidaridad, NCIV, Agriterra, Cordaid, Somo, TNI, ICCO, KIT, International Institute of Social Studies, Rijksuniversiteit Groningen, Kadaster, Universiteit Leiden, Universiteit Twente, Universiteit Utrecht, African Studies Centre, Atradius, National Contactpunt (NCP) OESO richtlijnen, Netherlands Ministry of Finance, Netherlands Ministry of Economic Affairs, Initiatief Duurzame Handel, LANDac": ["Ministry of Foreign Affairs of the Netherlands", "Rabobank", "ABN Amro", "ABP", "APG", "PGGM", "ACTIAM", "Pensioenfederatie", "ING", "FMO", "Aegon", "Dutch Banking Association (Nederlandse Vereniging van Banken)", "Coca Cola Company", "Van Oord", "Netherlands Agricultural and Horticultural Association (LTO Nederland)", "Oxfam Novib", "Both ENDS", "ActionAid", "Tropenbos International", "Friends of the Earth Netherlands (Milieudefensie)", "Hivos", "Solidaridad", "Netherlands Centre for Indigenous Peoples", "Agriterra", "Cordaid", "Centre for Research on Multinational Corporations (Stichting Onderzoek Multinationale Ondernemingen)", "Transnational Institute ", "ICCO", "International Institute of Social Studies", "University of Groningen", "University of Leiden", "Utrecht University", "African Studies Centre Leiden", "Atradius", "National Contact Point OECD Guidelines (Netherlands)", "Ministry of Finance of the Netherlands", "Ministry of Economic Affairs and Climate Policy of the Netherlands", "IDH, The Sustainable Trade Initiative", "LANDac"],
        "NiZa (Netherland's Institute for Southern Africa)": ["NiZa, Netherland's Institute for Southern Africa"],
        "Niras": ["NIRAS"],
        "North East Council (NEC)": ["Government of India"],
        "Norwegian Mapping Authority": ["Norwegian Mapping Authority (Kartverket)"],
        "Norwegian Refugee Council": ["Norwegian Refugee Council"],
        "Not applicable (Project Implementation Unit)": [],
        "ORAM": ["Associação Rural de Ajuda Mútua"],
        "OVERSEAS DEVELOPMENT INSTITUTE": ["Overseas Development Institute"],
        "OXFAM GB": ["Oxfam Great Britain"],
        "Open Society Justice Initiative (OSJI) within the Open Society Institute, Namati": ["Namati"],
        "Overseas Development Institute": ["Overseas Development Institute"],
        "Oxfam and Partners": ["Oxfam International"],
        "Oxfam and partners": ["Oxfam International"],
        "Oxfam, Oxfam partners": ["Oxfam International"],
        "PROCASUR": ["Procasur"],
        "PULITZER CENTER ON CRISIS REPORTING": ["Pulitzer Center on Crisis Reporting"],
        "PWC": ["PricewaterhouseCoopers"],
        "Palestine Land Authority, Niras": ["Palestine Land Authority", "NIRAS"],
        "Paraguay Ministry of Agriculture": ["Government of Paraguay"],
        "Plan International UK Ltd": ["Plan International UK Ltd"],
        "Planning &amp; Development Department, GoGB": ["Government of Pakistan"],
        "Poverty Alleviation Office of the Xinjiang Uygur Autonomous Region": ["Government of the People's Republic of China"],
        "Prayog Samaj Sevi Sanstha": ["Prayog Samaj Sevi Sanstha"],
        "Provincial People's Committees of Ha Tinh and Quang Binh": ["Government of Vietnam"],
        "Provincial People\xe2\x80\x99s Committee of Bac Kan Province": ["Government of Vietnam"],
        "RCN JUSTICE &amp; DEMOCRATIE ASBL": [u"RCN Justice & Démocratie"],
        "RCN, Justice &amp; D\xc3\xa9mocratie": [u"RCN Justice & Démocratie"],
        "Regional administrations of Debub and Gash Barka": ["Government of Eritrea"],
        "Regional government of Oromyia": ["Government of Ethiopia"],
        "Registro Informacion Catastral de Guatemala": ["Government of Guatemala"],
        "Rights and Resources Initiative": ["Rights and Resources Initiative"],
        "Rights and Resources Initiative (RRI)": ["Rights and Resources Initiative"],
        "Rural Development and Cooperatives Division (RDCD) of the Ministry of Local Government, Rural Development and Cooperatives": ["Government of Bangladesh"],
        "Rwanda Initiative for Sustainable Development (RISD)": ["Rwanda Initiative for Sustainable Development"],
        "Rwanda Natural Resource Authority, IBRD, Landesa, Crown Agents Bank, PwC Rwanda, Mott MacDonald, DAI Europe, Coffey International Development": ["Rwanda Natural Resources Authority","Crown Agents Bank", "PricewaterhouseCoopers", "Mott MacDonald", "DAI", "Coffey","International Bank for Reconstruction and Development", "Landesa"],
        "SEARCH FOR COMMON GROUND VZW": ["Search for Common Ground"],
        "SIDA": ["Swedish International Development Cooperation Agency (SIDA)"],
        "SNV": ["SNV"],
        "SNV and ICCO": ["SNV", "Organización Intereclesiástica para la Cooperación al Desarrollo Centroamérica"],
        "SNV and RECOFTC (Centre for People and Forests)": ["SNV", "The Center for People and Forests"],
        "SSG Advisors": ["SSG Advisors LLP"],
        "STICHTING OXFAM NOVIB (NOVIB)": ["Oxfam Novib"],
        "SYKE (Finnish Environment Institute)": ["Finnish Environment Institute"],
        "Scheduled Tribes and Scheduled Castes Development Department, Government of Odisha": ["Government of Odisha (India)"],
        "Secretaria de asuntos agrarios(SAA), Fundo de tierras, FAO": ["Government of Guatemala", "Fondo de Tierras (Guatemala)", "Food and Agriculture Organization of the United Nations (FAO)"],
        "Secretariat of State of Agrarian Development": ["Government of Brazil"],
        "Service Contracts": [],
        "Service contract": [],
        "Services Support Unit": [],
        "Single Project Implementation Unit of the Ministry of Agriculture and Animal Resources": ["Rwanda Ministry of Agriculture, Animal Resources, and Forestry"],
        "Sir Ratan Tata Trust": ["Tata Trusts"],
        "Social Investment Fund (FIS)": [],
        "Specialized Judicial Unit for Constitutional Development": ["Government of Bolivia"],
        "Springfield": ["Springfield Centre"],
        "Spruce": [],
        "State Authority of Geodetic Works (SAGW)": ["Government of the Republic of North Macedonia"],
        "State Department of the Ministry of Agriculture, Livestock and Fisheries": ["Government of Kenya"],
        "State Governments of Bihar and Madhya Pradesh through respective Tribal Development Societies (TDSs)": ["Government of Madhya Pradesh;Government of Bihar (India)"],
        "Stockholm International Water Institute SIWI/Swedish Meteorological and Hydrological Institute SMHI": ["Stockholm International Water Institute", "Government of Sweden"],
        "Surinam Ministry of Territorial Planning, Land- and Forestry Management": ["Government of Suriname"],
        "Surveyor General Office, Swaziland": ["Government of Eswatini"],
        "Suyo": ["Suyo"],
        "Swarna Pragati": ["Swarna Pragati"],
        "TBC": ["The Border Consortium"],
        "TMG Research gGmbH, CIAT, CETRAD (Kenya), GRAF (Burkina Faso)": ["TMG-ThinkTank for Sustainability", "International Center for Tropical Agriculture", "Center for Training and integreated Research in ASAL Development", "Groupe de Recherche et d'Action sur le Foncier"],
        "TMG Research, DIMR": ["TMG-ThinkTank for Sustainability", "Deutsches Institut für Menschenrechte"],
        "TREE AID": ["TREE AID"],
        "TRG": [],
        "Tecsult International Limited": ["AECOM"],
        "Tetra Tech": ["Tetra Tech"],
        "Tetra Tech ARD": ["Tetra Tech"],
        "Tetra Tech DPK": ["Tetra Tech"],
        "The Asia Foundation": ["The Asia Foundation"],
        "The Asia Foundation (International NGO) in collaboration with at least four national NGOs and selected district governments, civil society organisations and private sector stakeholders.": ["The Asia Foundation"],
        "The Asia Foundation (TAF), Crown Agents, IBRD, Yayasan Strategi Konservasi Indonesia, Yayasan KEHATI, World Business Councilc for Sustainable Development, Perkumpulan untuk Pembaharuan Hukum Berbasis Masyarakat dan Ekologis, Indonesia Climate Change Trust Fund.": ["The Asia Foundation", "Crown Agents", "International Bank for Reconstruction and Development", "Yayasan Strategi Konservasi Indonesia", "KEHATI Foundation", "World Business Council for Sustainable Development", "Perkumpulan untuk Pembaharuan Hukum Berbasis Masyarakat dan Ekologis", "Indonesia Climate Change Trust Fund" ],
        "The Foundation for Civil Society  and The Legal Services Facility": ["Foundation for Civil Society", "The Legal Services Facility"],
        "The Municipal Affairs Department is the lead. A Change Management Unit has been established under the Municipal Affairs Department to oversee the implementation of the programme.": ["Government of India"],
        "The Norwegian Mapping Authority": ["Norwegian Mapping Authority (Kartverket)"],
        "The Rainforest Foundation UK": ["Rainforest Foundation UK"],
        "The Swedish Mapping, Cadastral and Land Registration Authority": ["Lantmäteriet"],
        "The Urban Development and Housing Department headed by a Principle Secretary to the Government of Bihar. Implementation will be supported by an urban and technical support team contracted by DFID.": ["Government of Bihar (India)", "UK Department for International Development"],
        "Thomson Reuters Foundation": ["Thomson Reuters Foundation"],
        "Thomson Reuters, ILC": ["Thomson Reuters Foundation", "International Land Coalition"],
        "Transparency International": ["Transparency International"],
        "UN ECA": ["United Nations Economic Commission for Africa"],
        "UN HABITAT": ["United Nations Human Settlements Programme"],
        "UNDP": ["United Nations Development Programme"],
        "UNESCO": ["United Nations Educational Scientific and Cultural Organization"],
        "UNODC, GIZ": ["United Nations Office on Drugs and Crime", "Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH"],
        "UNOPS on behalf of UN-Habitat": ["United Nations Office for Project Services", "United Nations Human Settlements Programme"],
        "UNWomen and FAO in co-operation with a consortium of partners [Land Portal, OECD/SIGI, IFPRI, Landesa, International Land Coalition, World Bank LSMS, Oxfam, the Evidence and Data for Gender Equality (EDGE) initiative]": ["United Nations Entity for Gender Equality and the Empowerment of Women (UNWOMEN)", "Food and Agriculture Organization of the United Nations (FAO)", "Land Portal Foundation", "Organisation for Economic Co-operation and Development (OECD)", "Social Institutions & Gender Index", "International Food Policy Research Institute", "Landesa", "International Land Coalition", "World Bank Group", "Oxfam International", "United Nations Entity for Gender Equality and the Empowerment of Women (UNWOMEN)", "United Nations Statistics Division"],
        "UPPR, UN Habitat": ["United Nations Human Settlements Programme"],
        "US Forest Service\xe2\x80\x99s International Program (USFS-IP)": ["United States Department of Agriculture - Forest service"],
        "USAID": ["USAID"],
        "USDA-ARS": ["United States Department of Agriculture", "Agricultural Research Service (United States)"],
        "Unidad para el Cambio Rural (UCAR) from the Ministry of Agriculture, stock farming and fisheries": ["Government of Argentina"],
        "Universidad de San Carlos and ITC": ["Universidad de San Carlos de Guatemala"],
        "Universidad de San Carlos and ITC and Kadaster": ["Universidad de San Carlos de Guatemala", "Kadaster International"],
        "VLIR (Flemish Interuniversity Council)": ["Flemish Interuniversity Council"],
        "Village Focus International": ["Village Focus International"],
        "WFP": ["World Food Programme"],
        "Welthungerhilfe": ["Welthungerhilfe"],
        "Women for Women International, Women for Women DRC": ["Women for Women International"],
        "World Agroforestry Centre, DAI Europe, Rainforest Foundation UK, International Institute for Environment and Development": ["World Agroforestry Centre", "Rainforest Foundation UK", "DAI", "International Institute for Environment and Development"],
        "World Bank": ["World Bank Group"],
        "World Resources Institute": ["World Resources Institute"],
        "ZFD": ["Ziviler Friedensdienst"],
        "Zambian government and private sector, and coordinated  by the Ministry of Trade, Commerce and Industry": ["Government of Zambia"],
        "geAm, Environmental Management for Sustainable Development of Paraguay": ["geAm"],
        "various NGOs": []
    }.get(implementers, None)

    