#!/usr/bin/python
# -*- coding: UTF-8 -*-
import collections

def getUNM49code(label):
    return {
            'AFRICA': "002",
            'ASIA': "142",
            'CARIBBEAN': "029",
            'CENTRAL AFRICA': "017",
            'CENTRAL AMERICA': "013",
            'EAST AFRICA': "014",
            'EAST ASIA': "030",
            'NORTH AMERICA': "021",
            'NORTH AFRICA': "015",
            'SOUTH AMERICA': "005",
            'AFRICA SOUTH OF SAHARA' : "202",
            'SOUTHEAST ASIA': "035",
            'SOUTH AFRICA': "018",
            'SOUTHERN AFRICA': "018",
            'SOUTH ASIA': "034",
            'WEST AFRICA': "011",
            'WEST ASIA': "145",
            'PACIFIC': "009", # Manual map
            'AMAZONIA': None,
            'MIDDLE EAST': '145', #WESTERN ASIA
            "GLOBAL" : "001",
            "AFRICA" : "002",
            "SOUTH AMERICA" : "005",
            "OCEANIA" : "009",
            "WESTERN AFRICA" : "011",
            "CENTRAL AMERICA" : "013",
            "EASTERN AFRICA" : "014",
            "NORTHERN AFRICA" : "015",
            "MIDDLE AFRICA" : "017",
            "SOUTHERN AFRICA" : "018",
            "AMERICAS" : "019",
            "NORTHERN AMERICA" : "021",
            "CARIBBEAN" : "029",
            "EASTERN ASIA" : "030",
            "SOUTHERN ASIA" : "034",
            "SOUTH-EASTERN ASIA" : "035",
            "SOUTHERN EUROPE" : "039",
            "AUSTRALIA AND NEW ZEALAND" : "053",
            "MELANESIA" : "054",
            "MICRONESIA (REGION)" : "057",
            "POLYNESIA" : "061",
            "ASIA" : "142",
            "CENTRAL ASIA" : "143",
            "WESTERN ASIA" : "145",
            "EUROPE" : "150",
            "EASTERN EUROPE" : "151",
            "NORTHERN EUROPE" : "154",
            "WESTERN EUROPE" : "155",
            "SUB-SAHARAN AFRICA" : "202",
            "LATIN AMERICA AND THE CARIBBEAN" : "419",
            "SAHEL" : ["SEN", "MRT", "MLI", "BFA", "DZA", "NER", "NGA", "TCD", "SDN", "SSD", "ERI", "CMR", "CAF", "ETH"], # from wikipedia
            "WEST AND CENTRAL AFRICA": ['011','017'],
            "ACP": ["AGO", "ATG", "BLZ", "CPV", "COM", "BHS", "BRB", "BEN", "BWA", "BFA", "BDI", "CMR", "CAF", "TCD", "COG", "COD", "COK", "CIV", "CUB", "DJI", "DMA", "DOM", "ERI", "ETH", "FJI", "GAB", "GMB", "GHA", "GRD", "GIN", "GNB", "GNQ", "GUY", "HTI", "JAM", "KEN", "KIR", "LSO", "LBR", "MDG", "MWI", "MLI", "MHL", "MRT", "MUS", "FSM", "MOZ", "NAM", "NRU", "NER", "NGA", "NIU", "PLW", "PNG", "RWA", "KNA", "LCA", "VCT", "SLB", "WSM", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SDN", "SUR", "SWZ", "TZA", "TLS", "TGO", "TON", "TTO", "TUV", "UGA", "VUT", "ZMB", "ZWE"], # from http://www.acp.int/node/7
            "SOUTHERN  AFRICA" : "018",
            u"WEST\xa0AFRICA": '011',
            u'CENTRAL\xa0ASIA': "143",
            u'SOUTHERN\uffa0 AFRICA': "018",
            u'SOUTH EAST ASIA': "035",
            "LATIN AMERICA": ['013', '005'], # Central America    013 +  South America    005 CHECK    
            "CENTRAL EUROPE": ["AUS", "HRV", "CZE", "DEU", "HUN", "LIE", "POL", "SVK", "SVN", "CHE"], # it is not an element of the UN M49

    }.get(label.upper(), None)

def getISO3166_1code(label):
    return {
        "HONDURAS" : "HND",
        "AFRICA": None,
        "ANGOLA": "AGO",
        "BANGLADESH": "BGD",
        "BELIZE": "BLZ",
        "BENIN": "XXX",
        "BHUTAN": "BTN",
        "BOLIVIA": "BOL",
        "BOTSWANA": "BWA",
        "BRAZIL": "BRA",
        "BURKINA FASO": "BFA",
        "CAMBODIA": "KHM",
        "CAMEROON": "CMR",
        "CANADA": "CAN",
        "CENTRAL AFRICAN REPUBLIC": "CAF",
        "CHILE": "CHL",
        "CHINA": "CHN",
        "COLOMBIA": "COL",
        "CONGO, DR": "COD",
        "COSTA RICA": "CRI",
        "COTE D'IVOIRE": "CIV",
        "CUBA": "CUB",
        "DOMINICAN REPUBLIC": "DOM",
        "ECUADOR": "ECU",
        "EL SALVADOR": "SLV",
        "ETHIOPIA": "ETH",
        "GHANA": "GHA",
        "GUATEMALA": "GTM",
        "HAITI": "HTI",
        "HONDURAS": "HND",
        "INDIA": "IND",
        "INDONESIA": "IDN",
        "KENYA": "KEN",
        "KOREA, DPR": "PRK",
        "LAOS": "LAO",
        "MADAGASCAR": "MDG",
        "MALAWI": "MWI",
        "MALAYSIA": "MYS",
        "MALI": "MLI",
        "MEXICO": "MEX",
        "MOZAMBIQUE": "MOZ",
        "MYANMAR": "MMR",
        "NAMIBIA": "NAM",
        "NEPAL": "NPL",
        "NEW ZEALAND": "NZL",
        "NICARAGUA": "NIC",
        "NIGER": "NER",
        "NIGERIA": "NGA",
        "PAKISTAN": "PAK",
        "PANAMA": "PAN",
        "PAPUA NEW GUINEA": "PNG",
        "PARAGUAY": "PRY",
        "PERU": "PER",
        "PHILIPPINES": "PHL",
        "RWANDA": "RWA",
        "SENEGAL": "SEN",
        "SOLOMON ISLANDS": "SLB",
        "SOUTH AFRICA": "ZAF",
        "SRI LANKA": "LKA",
        "SUDAN": "SDN",
        "SWAZILAND": "SWZ",
        "TAJIKISTAN": "TJK",
        "TANZANIA": "TZA",
        "THAILAND": "THA",
        "TIBET": None,
        "UGANDA": "UGA",
        "URUGUAY": "URY",
        "VENEZUELA": "VEN",
        "VIETNAM": "VNM",
        "ZAMBIA": "XMB",
        "ZIMBABWE": "ZWE",
        "ARUBA" : "ABW",
        "AFGHANISTAN" : "AFG",
        "ANGOLA" : "AGO",
        "ANGUILLA" : "AIA",
        "ÅLAND ISLANDS" : "ALA",
        "ALBANIA" : "ALB",
        "ANDORRA" : "AND",
        "UNITED ARAB EMIRATES" : "ARE",
        "ARGENTINA" : "ARG",
        "ARMENIA" : "ARM",
        "AMERICAN SAMOA" : "ASM",
        "ANTARCTICA" : "ATA",
        "FRENCH SOUTHERN TERRITORIES" : "ATF",
        "ANTIGUA AND BARBUDA" : "ATG",
        "AUSTRALIA" : "AUS",
        "AUSTRIA" : "AUT",
        "AZERBAIJAN" : "AZE",
        "BURUNDI" : "BDI",
        "BELGIUM" : "BEL",
        "BENIN" : "BEN",
        "BONAIRE, SINT EUSTATIUS AND SABA" : "BES",
        "BURKINA FASO" : "BFA",
        "BANGLADESH" : "BGD",
        "BULGARIA" : "BGR",
        "BAHRAIN" : "BHR",
        "BAHAMAS" : "BHS",
        "BOSNIA AND HERZEGOVINA" : "BIH",
        "SAINT BARTHÉLEMY" : "BLM",
        "BELARUS" : "BLR",
        "BELIZE" : "BLZ",
        "BERMUDA" : "BMU",
        "BOLIVIA, PLURINATIONAL STATE OF" : "BOL",
        "BRAZIL" : "BRA",
        "BARBADOS" : "BRB",
        "BRUNEI DARUSSALAM" : "BRN",
        "BHUTAN" : "BTN",
        "BOUVET ISLAND" : "BVT",
        "BOTSWANA" : "BWA",
        "CENTRAL AFRICAN REPUBLIC" : "CAF",
        "CANADA" : "CAN",
        "COCOS (KEELING) ISLANDS" : "CCK",
        "SWITZERLAND" : "CHE",
        "CHILE" : "CHL",
        "CHINA" : "CHN",
        U"CÔTE D'IVOIRE" : "CIV",
        "CAMEROON" : "CMR",
        "CONGO, THE DEMOCRATIC REPUBLIC OF THE" : "COD",
        "CONGO" : "COG",
        "COOK ISLANDS" : "COK",
        "COLOMBIA" : "COL",
        "COMOROS" : "COM",
        "CABO VERDE" : "CPV",
        "CAPE VERDE" : "CPV",
        "COSTA RICA" : "CRI",
        "CUBA" : "CUB",
        "CURAÇAO" : "CUW",
        "CHRISTMAS ISLAND" : "CXR",
        "CAYMAN ISLANDS" : "CYM",
        "CYPRUS" : "CYP",
        "CZECHIA" : "CZE",
        "GERMANY" : "DEU",
        "DJIBOUTI" : "DJI",
        "DOMINICA" : "DMA",
        "DENMARK" : "DNK",
        "DOMINICAN REPUBLIC" : "DOM",
        "ALGERIA" : "DZA",
        "ECUADOR" : "ECU",
        "EGYPT" : "EGY",
        "ERITREA" : "ERI",
        "WESTERN SAHARA" : "ESH",
        "SPAIN" : "ESP",
        "ESTONIA" : "EST",
        "ETHIOPIA" : "ETH",
        "FINLAND" : "FIN",
        "FIJI" : "FJI",
        "FALKLAND ISLANDS (MALVINAS)" : "FLK",
        "FRANCE" : "FRA",
        "FAROE ISLANDS" : "FRO",
        "MICRONESIA, FEDERATED STATES OF" : "FSM",
        "GABON" : "GAB",
        "UNITED KINGDOM" : "GBR",
        "GEORGIA" : "GEO",
        "GUERNSEY" : "GGY",
        "GHANA" : "GHA",
        "GIBRALTAR" : "GIB",
        "GUINEA" : "GIN",
        "GUADELOUPE" : "GLP",
        "GAMBIA" : "GMB",
        "GUINEA-BISSAU" : "GNB",
        "EQUATORIAL GUINEA" : "GNQ",
        "GREECE" : "GRC",
        "GRENADA" : "GRD",
        "GREENLAND" : "GRL",
        "GUATEMALA" : "GTM",
        "FRENCH GUIANA" : "GUF",
        "GUAM" : "GUM",
        "GUYANA" : "GUY",
        "HONG KONG" : "HKG",
        "HEARD ISLAND AND MCDONALD ISLANDS" : "HMD",
        "HONDURAS" : "HND",
        "CROATIA" : "HRV",
        "HAITI" : "HTI",
        "HUNGARY" : "HUN",
        "INDONESIA" : "IDN",
        "ISLE OF MAN" : "IMN",
        "INDIA" : "IND",
        "BRITISH INDIAN OCEAN TERRITORY" : "IOT",
        "IRELAND" : "IRL",
        "IRAN, ISLAMIC REPUBLIC OF" : "IRN",
        "IRAQ" : "IRQ",
        "ICELAND" : "ISL",
        "ISRAEL" : "ISR",
        "ITALY" : "ITA",
        "JAMAICA" : "JAM",
        "JERSEY" : "JEY",
        "JORDAN" : "JOR",
        "JAPAN" : "JPN",
        "KAZAKHSTAN" : "KAZ",
        "KENYA" : "KEN",
        "KYRGYZSTAN" : "KGZ",
        "CAMBODIA" : "KHM",
        "KIRIBATI" : "KIR",
        "SAINT KITTS AND NEVIS" : "KNA",
        "KOREA, REPUBLIC OF" : "KOR",
        "KUWAIT" : "KWT",
        "LAO PEOPLE'S DEMOCRATIC REPUBLIC" : "LAO",
        "LEBANON" : "LBN",
        "LIBERIA" : "LBR",
        "LIBYA" : "LBY",
        "SAINT LUCIA" : "LCA",
        "LIECHTENSTEIN" : "LIE",
        "SRI LANKA" : "LKA",
        "LESOTHO" : "LSO",
        "LITHUANIA" : "LTU",
        "LUXEMBOURG" : "LUX",
        "LATVIA" : "LVA",
        "MACAO" : "MAC",
        "SAINT MARTIN (FRENCH PART)" : "MAF",
        "MOROCCO" : "MAR",
        "MONACO" : "MCO",
        "MOLDOVA, REPUBLIC OF" : "MDA",
        "MADAGASCAR" : "MDG",
        "MALDIVES" : "MDV",
        "MEXICO" : "MEX",
        "MARSHALL ISLANDS" : "MHL",
        "MACEDONIA, REPUBLIC OF" : "MKD",
        "MALI" : "MLI",
        "MALTA" : "MLT",
        "MYANMAR" : "MMR",
        "MONTENEGRO" : "MNE",
        "MONGOLIA" : "MNG",
        "NORTHERN MARIANA ISLANDS" : "MNP",
        "MOZAMBIQUE" : "MOZ",
        "MAURITANIA" : "MRT",
        "MONTSERRAT" : "MSR",
        "MARTINIQUE" : "MTQ",
        "MAURITIUS" : "MUS",
        "MALAWI" : "MWI",
        "MALAYSIA" : "MYS",
        "MAYOTTE" : "MYT",
        "NAMIBIA" : "NAM",
        "NEW CALEDONIA" : "NCL",
        "NIGER" : "NER",
        "NORFOLK ISLAND" : "NFK",
        "NIGERIA" : "NGA",
        "NICARAGUA" : "NIC",
        "NIUE" : "NIU",
        "NETHERLANDS" : "NLD",
        "NORWAY" : "NOR",
        "NEPAL" : "NPL",
        "NAURU" : "NRU",
        "NEW ZEALAND" : "NZL",
        "OMAN" : "OMN",
        "PAKISTAN" : "PAK",
        "PANAMA" : "PAN",
        "PITCAIRN" : "PCN",
        "PERU" : "PER",
        "PHILIPPINES" : "PHL",
        "PALAU" : "PLW",
        "PAPUA NEW GUINEA" : "PNG",
        "POLAND" : "POL",
        "PUERTO RICO" : "PRI",
        "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" : "PRK",
        "PORTUGAL" : "PRT",
        "PARAGUAY" : "PRY",
        "PALESTINE, STATE OF" : "PSE",
        "FRENCH POLYNESIA" : "PYF",
        "QATAR" : "QAT",
        "RÉUNION" : "REU",
        "ROMANIA" : "ROU",
        "RUSSIAN FEDERATION" : "RUS",
        "RWANDA" : "RWA",
        "SAUDI ARABIA" : "SAU",
        "SUDAN" : "SDN",
        "SENEGAL" : "SEN",
        "SINGAPORE" : "SGP",
        "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" : "SGS",
        "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" : "SHN",
        "SVALBARD AND JAN MAYEN" : "SJM",
        "SOLOMON ISLANDS" : "SLB",
        "SIERRA LEONE" : "SLE",
        "EL SALVADOR" : "SLV",
        "SAN MARINO" : "SMR",
        "SOMALIA" : "SOM",
        "SAINT PIERRE AND MIQUELON" : "SPM",
        "SERBIA" : "SRB",
        "SOUTH SUDAN" : "SSD",
        "SAO TOME AND PRINCIPE" : "STP",
        "SURINAME" : "SUR",
        "SLOVAKIA" : "SVK",
        "SLOVENIA" : "SVN",
        "SWEDEN" : "SWE",
        "SWAZILAND" : "SWZ",
        "SINT MAARTEN (DUTCH PART)" : "SXM",
        "SEYCHELLES" : "SYC",
        "SYRIAN ARAB REPUBLIC" : "SYR",
        "TURKS AND CAICOS ISLANDS" : "TCA",
        "CHAD" : "TCD",
        "TOGO" : "TGO",
        "THAILAND" : "THA",
        "TAJIKISTAN" : "TJK",
        "TOKELAU" : "TKL",
        "TURKMENISTAN" : "TKM",
        "TIMOR-LESTE" : "TLS",
        "TONGA" : "TON",
        "TRINIDAD AND TOBAGO" : "TTO",
        "TUNISIA" : "TUN",
        "TURKEY" : "TUR",
        "TUVALU" : "TUV",
        "TAIWAN, PROVINCE OF CHINA" : "TWN",
        "TANZANIA, UNITED REPUBLIC OF" : "TZA",
        "UGANDA" : "UGA",
        "UKRAINE" : "UKR",
        "UNITED STATES MINOR OUTLYING ISLANDS" : "UMI",
        "URUGUAY" : "URY",
        "UNITED STATES" : "USA",
        "UZBEKISTAN" : "UZB",
        "HOLY SEE (VATICAN CITY STATE)" : "VAT",
        "SAINT VINCENT AND THE GRENADINES" : "VCT",
        "VENEZUELA, BOLIVARIAN REPUBLIC OF" : "VEN",
        "VIRGIN ISLANDS, BRITISH" : "VGB",
        "VIRGIN ISLANDS, U.S." : "VIR",
        "VIET NAM" : "VNM",
        "VANUATU" : "VUT",
        "WALLIS AND FUTUNA" : "WLF",
        "SAMOA" : "WSM",
        "YEMEN" : "YEM",
        "SOUTH AFRICA" : "ZAF",
        "ZAMBIA" : "ZMB",
        "ZIMBABWE" : "ZWE",
        "BOLIVIA" : "BOL",
        "MOLDOVA" : "MDA",
        "TAIWAN" : "TWN",
        "TANZANIA" : "TZA",
        "VENEZUELA" : "VEN",
        "VIETNAM" : "VNM",
        "ISLAMIC REPUBLIC OF AFGHANISTAN" : "AFG",
        "REPUBLIC OF ANGOLA" : "AGO",
        "REPUBLIC OF ALBANIA" : "ALB",
        "PRINCIPALITY OF ANDORRA" : "AND",
        "ARGENTINE REPUBLIC" : "ARG",
        "REPUBLIC OF ARMENIA" : "ARM",
        "REPUBLIC OF AUSTRIA" : "AUT",
        "REPUBLIC OF AZERBAIJAN" : "AZE",
        "REPUBLIC OF BURUNDI" : "BDI",
        "KINGDOM OF BELGIUM" : "BEL",
        "REPUBLIC OF BENIN" : "BEN",
        "BONAIRE, SINT EUSTATIUS AND SABA" : "BES",
        "PEOPLE'S REPUBLIC OF BANGLADESH" : "BGD",
        "REPUBLIC OF BULGARIA" : "BGR",
        "KINGDOM OF BAHRAIN" : "BHR",
        "COMMONWEALTH OF THE BAHAMAS" : "BHS",
        "REPUBLIC OF BOSNIA AND HERZEGOVINA" : "BIH",
        "REPUBLIC OF BELARUS" : "BLR",
        "PLURINATIONAL STATE OF BOLIVIA" : "BOL",
        "FEDERATIVE REPUBLIC OF BRAZIL" : "BRA",
        "KINGDOM OF BHUTAN" : "BTN",
        "REPUBLIC OF BOTSWANA" : "BWA",
        "SWISS CONFEDERATION" : "CHE",
        "REPUBLIC OF CHILE" : "CHL",
        "PEOPLE'S REPUBLIC OF CHINA" : "CHN",
        "REPUBLIC OF CÔTE D'IVOIRE" : "CIV",
        "REPUBLIC OF CAMEROON" : "CMR",
        "REPUBLIC OF THE CONGO" : "COG",
        "REPUBLIC OF COLOMBIA" : "COL",
        "UNION OF THE COMOROS" : "COM",
        "REPUBLIC OF CABO VERDE" : "CPV",
        "REPUBLIC OF COSTA RICA" : "CRI",
        "REPUBLIC OF CUBA" : "CUB",
        "CURAÇAO" : "CUW",
        "REPUBLIC OF CYPRUS" : "CYP",
        "CZECH REPUBLIC" : "CZE",
        "FEDERAL REPUBLIC OF GERMANY" : "DEU",
        "REPUBLIC OF DJIBOUTI" : "DJI",
        "COMMONWEALTH OF DOMINICA" : "DMA",
        "KINGDOM OF DENMARK" : "DNK",
        "PEOPLE'S DEMOCRATIC REPUBLIC OF ALGERIA" : "DZA",
        "REPUBLIC OF ECUADOR" : "ECU",
        "ARAB REPUBLIC OF EGYPT" : "EGY",
        "THE STATE OF ERITREA" : "ERI",
        "KINGDOM OF SPAIN" : "ESP",
        "REPUBLIC OF ESTONIA" : "EST",
        "FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA" : "ETH",
        "REPUBLIC OF FINLAND" : "FIN",
        "REPUBLIC OF FIJI" : "FJI",
        "FRENCH REPUBLIC" : "FRA",
        "FEDERATED STATES OF MICRONESIA" : "FSM",
        "GABONESE REPUBLIC" : "GAB",
        "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND" : "GBR",
        "REPUBLIC OF GHANA" : "GHA",
        "REPUBLIC OF GUINEA" : "GIN",
        "ISLAMIC REPUBLIC OF THE GAMBIA" : "GMB",
        "REPUBLIC OF GUINEA-BISSAU" : "GNB",
        "REPUBLIC OF EQUATORIAL GUINEA" : "GNQ",
        "HELLENIC REPUBLIC" : "GRC",
        "REPUBLIC OF GUATEMALA" : "GTM",
        "REPUBLIC OF GUYANA" : "GUY",
        "HONG KONG SPECIAL ADMINISTRATIVE REGION OF CHINA" : "HKG",
        "REPUBLIC OF HONDURAS" : "HND",
        "REPUBLIC OF CROATIA" : "HRV",
        "REPUBLIC OF HAITI" : "HTI",
        "HUNGARY" : "HUN",
        "REPUBLIC OF INDONESIA" : "IDN",
        "REPUBLIC OF INDIA" : "IND",
        "ISLAMIC REPUBLIC OF IRAN" : "IRN",
        "REPUBLIC OF IRAQ" : "IRQ",
        "REPUBLIC OF ICELAND" : "ISL",
        "STATE OF ISRAEL" : "ISR",
        "ITALIAN REPUBLIC" : "ITA",
        "HASHEMITE KINGDOM OF JORDAN" : "JOR",
        "REPUBLIC OF KAZAKHSTAN" : "KAZ",
        "REPUBLIC OF KENYA" : "KEN",
        "KYRGYZ REPUBLIC" : "KGZ",
        "KINGDOM OF CAMBODIA" : "KHM",
        "REPUBLIC OF KIRIBATI" : "KIR",
        "STATE OF KUWAIT" : "KWT",
        "LEBANESE REPUBLIC" : "LBN",
        "REPUBLIC OF LIBERIA" : "LBR",
        "LIBYA" : "LBY",
        "PRINCIPALITY OF LIECHTENSTEIN" : "LIE",
        "DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA" : "LKA",
        "KINGDOM OF LESOTHO" : "LSO",
        "REPUBLIC OF LITHUANIA" : "LTU",
        "GRAND DUCHY OF LUXEMBOURG" : "LUX",
        "REPUBLIC OF LATVIA" : "LVA",
        "MACAO SPECIAL ADMINISTRATIVE REGION OF CHINA" : "MAC",
        "KINGDOM OF MOROCCO" : "MAR",
        "PRINCIPALITY OF MONACO" : "MCO",
        "REPUBLIC OF MOLDOVA" : "MDA",
        "REPUBLIC OF MADAGASCAR" : "MDG",
        "REPUBLIC OF MALDIVES" : "MDV",
        "UNITED MEXICAN STATES" : "MEX",
        "REPUBLIC OF THE MARSHALL ISLANDS" : "MHL",
        "THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA" : "MKD",
        "REPUBLIC OF MALI" : "MLI",
        "REPUBLIC OF MALTA" : "MLT",
        "REPUBLIC OF MYANMAR" : "MMR",
        "MONTENEGRO" : "MNE",
        "COMMONWEALTH OF THE NORTHERN MARIANA ISLANDS" : "MNP",
        "REPUBLIC OF MOZAMBIQUE" : "MOZ",
        "ISLAMIC REPUBLIC OF MAURITANIA" : "MRT",
        "REPUBLIC OF MAURITIUS" : "MUS",
        "REPUBLIC OF MALAWI" : "MWI",
        "REPUBLIC OF NAMIBIA" : "NAM",
        "REPUBLIC OF THE NIGER" : "NER",
        "FEDERAL REPUBLIC OF NIGERIA" : "NGA",
        "REPUBLIC OF NICARAGUA" : "NIC",
        "NIUE" : "NIU",
        "KINGDOM OF THE NETHERLANDS" : "NLD",
        "KINGDOM OF NORWAY" : "NOR",
        "FEDERAL DEMOCRATIC REPUBLIC OF NEPAL" : "NPL",
        "REPUBLIC OF NAURU" : "NRU",
        "SULTANATE OF OMAN" : "OMN",
        "ISLAMIC REPUBLIC OF PAKISTAN" : "PAK",
        "REPUBLIC OF PANAMA" : "PAN",
        "REPUBLIC OF PERU" : "PER",
        "REPUBLIC OF THE PHILIPPINES" : "PHL",
        "REPUBLIC OF PALAU" : "PLW",
        "INDEPENDENT STATE OF PAPUA NEW GUINEA" : "PNG",
        "REPUBLIC OF POLAND" : "POL",
        "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA" : "PRK",
        "PORTUGUESE REPUBLIC" : "PRT",
        "REPUBLIC OF PARAGUAY" : "PRY",
        "THE STATE OF PALESTINE" : "PSE",
        "STATE OF QATAR" : "QAT",
        "RWANDESE REPUBLIC" : "RWA",
        "KINGDOM OF SAUDI ARABIA" : "SAU",
        "REPUBLIC OF THE SUDAN" : "SDN",
        "REPUBLIC OF SENEGAL" : "SEN",
        "REPUBLIC OF SINGAPORE" : "SGP",
        "REPUBLIC OF SIERRA LEONE" : "SLE",
        "REPUBLIC OF EL SALVADOR" : "SLV",
        "REPUBLIC OF SAN MARINO" : "SMR",
        "FEDERAL REPUBLIC OF SOMALIA" : "SOM",
        "REPUBLIC OF SERBIA" : "SRB",
        "REPUBLIC OF SOUTH SUDAN" : "SSD",
        "DEMOCRATIC REPUBLIC OF SAO TOME AND PRINCIPE" : "STP",
        "REPUBLIC OF SURINAME" : "SUR",
        "SLOVAK REPUBLIC" : "SVK",
        "REPUBLIC OF SLOVENIA" : "SVN",
        "KINGDOM OF SWEDEN" : "SWE",
        "KINGDOM OF SWAZILAND" : "SWZ",
        "SINT MAARTEN (DUTCH PART)" : "SXM",
        "REPUBLIC OF SEYCHELLES" : "SYC",
        "REPUBLIC OF CHAD" : "TCD",
        "TOGOLESE REPUBLIC" : "TGO",
        "KINGDOM OF THAILAND" : "THA",
        "REPUBLIC OF TAJIKISTAN" : "TJK",
        "DEMOCRATIC REPUBLIC OF TIMOR-LESTE" : "TLS",
        "KINGDOM OF TONGA" : "TON",
        "REPUBLIC OF TRINIDAD AND TOBAGO" : "TTO",
        "REPUBLIC OF TUNISIA" : "TUN",
        "REPUBLIC OF TURKEY" : "TUR",
        "TAIWAN, PROVINCE OF CHINA" : "TWN",
        "UNITED REPUBLIC OF TANZANIA" : "TZA",
        "REPUBLIC OF UGANDA" : "UGA",
        "EASTERN REPUBLIC OF URUGUAY" : "URY",
        "UNITED STATES OF AMERICA" : "USA",
        "REPUBLIC OF UZBEKISTAN" : "UZB",
        "BOLIVARIAN REPUBLIC OF VENEZUELA" : "VEN",
        "BRITISH VIRGIN ISLANDS" : "VGB",
        "VIRGIN ISLANDS OF THE UNITED STATES" : "VIR",
        "SOCIALIST REPUBLIC OF VIET NAM" : "VNM",
        "REPUBLIC OF VANUATU" : "VUT",
        "INDEPENDENT STATE OF SAMOA" : "WSM",
        "REPUBLIC OF YEMEN" : "YEM",
        "REPUBLIC OF SOUTH AFRICA" : "ZAF",
        "REPUBLIC OF ZAMBIA" : "ZMB",
        "REPUBLIC OF ZIMBABWE" : "ZWE",
        "BOLIVIA (PLURINATIONAL STATE OF)" : "BOL",
        "BRUNEI" : "BRN",
        "BURKINA" : "BFA",
        "BURMA" : "MMR",
        "DEMOCRATIC REPUBLIC OF CONGO": "COD",
        "DEMOCRATIC REPUBLIC OF THE CONGO": "COD",
        "EAST TIMOR": "TLS",
        "HOLY SEE": "VAT",
        "IRAN": "IRN",
        "IRAN (ISLAMIC REPUBLIC OF)": "IRN",
        "IVORY COAST": "CIV",
        "KOREA": "KOR",
        "LAOS": "LAO",
        "MACEDONIA": "MKD",
        "MICRONESIA": "FSM",
        "MICRONESIA (FEDERATED STATES OF)": "FSM",
        "REPUBLIC OF KOREA": "KOR",
        "KOREA, REPUBLIC": "KOR",
        "SOUTH KOREA": "KOR",
        "SYRIA": "SYR",
        "THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA": "MKD",
        "VATICAN CITY": "VAT",
        "VENEZUELA (BOLIVARIAN REPUBLIC OF)": "VEN",
        "GLOBAL": "001", # World area UN M49
        "USA": "USA",
        "PALESTINE" : "PSE",        
        "RUSSIA": "RUS",
        "ZAIRE": None,
        "BORNEO": ["MYS","BRN", "IDN"],
        "WESTERN AUSTRALIA": "AUS",
        "LAO PDR": "LAO",
        "PERú": "PER",
        "INDONESIAN FORESTS": "IDN",
        "LAO TROPICAL DEFORESTATION": "LAO",
    }.get(label.upper(), None)


def getISO639_1code(label):
    return {
        "Albanian" : "sq",
        "Arabic" : "ar",
        "Azerbaijani" : "az",
        "Bosnian" : "bs",
        "Bulgarian" : "bg",
        "Catalan" : "ca",
        "Chinese" : "zh",
        "Chineset" : "zh",
        "Croatian" : "hr",
        "Czech" : "cs",
        "Danish" : "da",
        "Dutch" : "nl",
        "English" : "en",
        "Farsi" : "fa",
        "French" : "fr",
        "German" : "de",
        "Greek" : "el",
        "Hungarian" : "hu",
        "Indonesian" : "id",
        "Italian" : "it",
        "Macedonian" : "mk",
        "Montenegrin" : "sr",
        "Norwegian" : "no",
        "Polish" : "pl",
        "Portuguese" : "pt",
        "Russian" : "ru",
        "Serbian" : "sr",
        "Slovak" : "sk",
        "Slovenian" : "sl",
        "Spanish" : "es",
        "Swedish" : "sv",
        "Turkish" : "tr",
        "Ukrainian" : "uk",
    }[label]


def getLLR_type(label):
    return {
        None: "Other",
    }[label]

def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and not isinstance(el, basestring):
            for sub in flatten(el):
                yield sub
        else:
            yield el

# dev_contries = ["Algeria", "Egypt", "Libya", "Mauritania", "Morocco", "Sudan", "Tunisia", "Angola", "Botswana", "Lesotho", "Malawi", "Mauritius", "Mozambique", "Namibia", "South Africa", "Zambia", "Zimbabwe", "Brunei Darussalam", "China", "Hong Kong", "Indonesia", "Malaysia", "Myanmar", "Papua New Guinea", "Philippines", "Republic of Korea", "Singapore", "Thailand", "Viet Nam", "Barbados", "Cuba", "Dominican Republic", "Guyana", "Haiti", "Jamaica", "Trinidad and Tobago", "Cameroon", "Central African Republic", "Chad", "Congo", "Equatorial Guinea", "Gabon", "Sao Tome and Principe", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama", "Benin", "Burkina Faso", "Cabo Verde", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Liberia", "Mali", "Niger", "Nigeria", "Senegal", "Sierra Leone", "Togo", "Bangladesh", "India", "Iran (Islamic Republic of)", "Nepal", "Pakistan", "Sri Lanka", "Burundi", "Comoros", "Democratic Republic of the Congo", "Djibouti", "Eritrea", "Ethiopia", "Kenya", "Madagascar", "Rwanda", "Somalia", "Uganda", "United Republic of Tanzania", "Argentina", "Bolivia (Plurinational State of)", "Brazil", "Chile", "Colombia", "Ecuador", "Paraguay", "Peru", "Uruguay", "Venezuela (Bolivarian Republic of)", "Bahrain", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon", "Oman", "Qatar", "Saudi Arabia", "Syria", "Turkey", "United Arab Emirates", "Yemen", "COTE D'IVOIRE"]
# for c in dev_contries:
#     print "<http://data.landportal.info/geo/"+getISO3166_1code(c.upper())+">"