PREFIX cex: <http://purl.org/weso/ontology/computex#>

SELECT DISTINCT ?countryURL ?countryISO3 ?countryLabel
FROM <http://data.landportal.info>
WHERE {
   ?obs cex:ref-indicator <http://data.landportal.info/indicator/FAO-23045-6083> ;
        cex:ref-area ?countryURL .
   ?countryURL rdfs:label ?countryLabel.
   BIND (REPLACE(STR(?countryURL), "http://data.landportal.info/geo/","") AS ?countryISO3)
} ORDER BY ?countryLabel
