# Get indicators that have, at least two values for a country.
# Returns indicatorURL and indicatorLabel
# Ordered by indicatorURL
# For debugging, query SELECT DISTINCT ?indicatorURL ?indicatorLabel (count(?obs) as ?count)

PREFIX cex: <http://purl.org/weso/ontology/computex#>

SELECT DISTINCT ?indicatorURL ?indicatorLabel
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-indicator ?indicatorURL ;
     cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:value ?value.
?indicatorURL rdfs:label ?indicatorLabel .
} 
GROUP BY ?indicatorURL ?indicatorLabel
HAVING (COUNT(?obs) >= 2)
ORDER BY ?indicatorURL
