PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?llr ?llrLabel ?country ?countryLabel
FROM <http://library.landportal.info>
WHERE {
   ?llr a  bibo:Document ;
        dct:spatial ?country ;
        dct:title ?llrLabel .
   ?country dct:identifier ?iso3 ;
        rdfs:label ?countryLabel .
FILTER ( ?iso3 = "BRA" || ?iso3 = "BOL" || ?iso3 = "ECU" || ?iso3 = "PER" || ?iso3 = "USA")
}
ORDER BY ?llr


