PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?countryISO3 (year(?dateTime) as ?year) ?value 
FROM <http://data.landportal.info>
WHERE {

?obs cex:ref-indicator ?indicatorURL ;
     cex:ref-area ?countryURL ;
     cex:ref-time ?time ;
     cex:value ?value.
     	 
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime .

VALUES ?indicatorURL {<http://data.landportal.info/indicator/FAO-23045-6083>}

BIND (REPLACE(STR(?countryURL), "http://data.landportal.info/geo/","") AS ?countryISO3)
	 
}
ORDER BY ?dateTime ?countryURL