# Get information about an indicator
PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>

SELECT ?indicatorLabel ?indicatorDescription ?indicatorUnit ?datasetURL ?datasetLabel ?sourceOrgURL ?sourceOrgLabel
FROM <http://indicators.landportal.info>
FROM <http://datasets.landportal.info>
FROM <http://organizations.landportal.info>
WHERE {
  ?indicator rdfs:label ?indicatorLabel ;
  dct:description ?indicatorDescription ;
  sdmx-attribute:unitMeasure ?indicatorUnit ;
  dct:source ?datasetURL .

  ?datasetURL rdfs:label ?datasetLabel ;
			  dct:publisher ?sourceOrgURL .
	
  ?sourceOrgURL rdfs:label ?sourceOrgLabel.

VALUES ?indicator {<http://data.landportal.info/indicator/FAO-23045-6083>}
}
