# Gets URL, LABEL and DESCRIPTION of all the indicators, ordered alphabetically by label.
# NOTE: the properties for label and description MUST change

PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX ex: <http://www.example.org/rdf#>

SELECT * 
FROM <http://data.landportal.info>
WHERE {
?indicatorUrl a cex:Indicator ;
	ex:label ?label ;
    ex:description ?description .
	# rdfs:label ?label ;
	# skos:definition ?description .
}
ORDER BY ?label
