PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT (?datasetOrg AS ?orgURI) ?orgLabel ?orgAcronym ?seeAlso
FROM <http://data.landportal.info>

WHERE {
?datasetURI dct:publisher ?datasetOrg
 OPTIONAL { ?datasetOrg rdfs:label ?orgLabel}
 OPTIONAL { ?datasetOrg skos:notation ?orgAcronym}
 OPTIONAL { ?datasetOrg rdfs:seeAlso ?seeAlso}

}
