#NOTE: This SPARQL query was used at the begging. Probably nowadays it is deprecated.

PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>

SELECT ?obs ?indicatorURL ?indicatorSeeAlso ?indicatorLabel ?indicatorDescription (year(?dateTime) as ?year) ?value ?unitLabel ?datasetURL ?datasetSeeAlso ?datasetLabel ?sourceURL ?sourceLabel ?sourceSeeAlso
FROM <http://data.landportal.info>
FROM <http://indicators.landportal.info>
FROM <http://datasets.landportal.info>
FROM <http://organizations.landportal.info>

WHERE {
?obs cex:ref-indicator ?indicatorURL ;
     cex:ref-time ?time ;
     cex:value ?value.
     	 
     ?indicatorURL rdfs:label ?indicatorLabel ;
                   dct:description ?indicatorDescription ;
		   rdfs:seeAlso ?indicatorSeeAlso;
		   sdmx-attribute:unitMeasure ?unitLabel ;
		   dct:source ?datasetURL .
				   
	 ?datasetURL rdfs:label ?datasetLabel ;
	  	     rdfs:seeAlso ?datasetSeeAlso;
	             dct:publisher ?sourceURL .

				   
	 ?sourceURL rdfs:label ?sourceLabel ;
	 	    rdfs:seeAlso ?sourceSeeAlso .
	 
     ?time time:hasBeginning ?timeValue .
     ?timeValue time:inXSDDateTime ?dateTime
 
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/WB-SP.POP.TOTL> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
} 
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/WB-SP.RUR.TOTL.ZS> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/WB-NY.GDP.PCAP.PP.KD> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/FAO-6601-5110> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/FAO-23045-6083> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/DP-MOD-O-F> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/DP-MOD-O-N> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}
UNION
{
SELECT ?obs 
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/FAO-LG.1FB> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime }
ORDER BY DESC(?dateTime)
LIMIT 1
}


}
