PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT (year(?dateTime) as ?year)
FROM <http://data.landportal.info>
WHERE {
?obs cex:ref-area <http://data.landportal.info/geo/TZA> ;
     cex:ref-indicator <http://data.landportal.info/indicator/FAO-23045-6083> ;
     cex:ref-time ?time .
?time time:hasBeginning ?timeValue .
?timeValue time:inXSDDateTime ?dateTime
}
ORDER BY DESC(?dateTime)
