PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?indicatorLabel ?indicatorDescription ?year ?value ?unitLabel ?datasetURL ?datasetLabel ?sourceOrgURL ?sourceOrgLabel
FROM <http://data.landportal.info>
WHERE {

?obs cex:ref-area ?countryURL ;
     cex:ref-indicator ?indicatorURL ;
     cex:value ?value ;
     cex:ref-time ?time .

?time time:hasBeginning ?timeValue .

?timeValue time:inXSDDateTime ?dateTime .

?indicatorURL sdmx-attribute:unitMeasure ?unitLabel ;
     dct:source ?datasetURL .
				   
?datasetURL rdfs:label ?datasetLabel ;
     dct:publisher ?sourceOrgURL .
	
?sourceOrgURL rdfs:label ?sourceOrgLabel.

?indicatorURL rdfs:label ?indicatorLabel ;
              dct:description ?indicatorDescription .

BIND (STR(YEAR(?dateTime)) AS ?year)

VALUES ?countryURL { <http://data.landportal.info/geo/VNM> }
VALUES ?indicatorURL { <http://data.landportal.info/indicator/FAO-23045-6083> }
VALUES ?year {'2007'}
}
