# Get indicators from a dataset
# Returns ?indicatorURL ?indicatorID ?indicatorLabel ?indicatorDescription
# Ordered by indicatorURL

PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?indicatorURL ?indicatorID ?indicatorLabel ?indicatorDescription 
FROM <http://data.landportal.info>
WHERE {
	?indicatorURL dct:source ?dataset.
	?indicatorURL skos:notation ?indicatorID ;
				rdfs:label ?indicatorLabel ;
				dct:description ?indicatorDescription .
	VALUES ?dataset {<http://data.landportal.info/dataset/NKT-VGGT16>}

} ORDER BY ?indicatorURL
