#!/usr/bin/python
# -*- coding: UTF-8 -*-

HARVEST_LIST = {
    "alienation (land)" : "http://aims.fao.org/aos/agrovoc/c_ceb73ce1",
    "assignment (land)" : "http://aims.fao.org/aos/agrovoc/c_8c6882ab",
    "cadastral administration" : "http://aims.fao.org/aos/agrovoc/c_d774aa00",
    "cadastral register" : "http://aims.fao.org/aos/agrovoc/c_b4d51db0",
    "cadastres" : "http://aims.fao.org/aos/agrovoc/c_1177",
    "capital value (land)" : "http://aims.fao.org/aos/agrovoc/c_a9966ac9",
    "co-ownership rights" : "http://aims.fao.org/aos/agrovoc/c_599d2e5c",
    "collateral (land)" : "http://aims.fao.org/aos/agrovoc/c_931da360",
    "concession (land)" : "http://aims.fao.org/aos/agrovoc/c_357653f9",
    "customary land rights" : "http://aims.fao.org/aos/agrovoc/c_cd44c0b3",
    "customary tenure" : "http://aims.fao.org/aos/agrovoc/c_56c34d4d",
    "dowry (land)" : "http://aims.fao.org/aos/agrovoc/c_f7cf8606",
    "encroachment" : "http://aims.fao.org/aos/agrovoc/c_a245096c",
    "eviction" : "http://aims.fao.org/aos/agrovoc/c_0b88a82c",
    "expropriation" : "http://aims.fao.org/aos/agrovoc/c_1798",
    "extensive land use" : "http://aims.fao.org/aos/agrovoc/c_36552",
    "forest conservation" : "http://aims.fao.org/aos/agrovoc/c_1374158672853",
    "gender equity in access to land" : "http://aims.fao.org/aos/agrovoc/c_1dfe5bfe",
    "grazing land rights" : "http://aims.fao.org/aos/agrovoc/c_97241aeb",
    "indigenous land rights" : "http://aims.fao.org/aos/agrovoc/c_d42b49e7",
    "indigenous lands" : "http://aims.fao.org/aos/agrovoc/c_86524ff8",
    "indigenous tenure" : "http://aims.fao.org/aos/agrovoc/c_a291ae58",
    "indigenous tenure systems" : "http://aims.fao.org/aos/agrovoc/c_9000081",
    "individual land property" : "http://aims.fao.org/aos/agrovoc/c_9000082",
    "intensive land use" : "http://aims.fao.org/aos/agrovoc/c_36551",
#    "land" : "http://aims.fao.org/aos/agrovoc/c_4172",
    "land access" : "http://aims.fao.org/aos/agrovoc/c_9000090",
    "land acquisitions" : "http://aims.fao.org/aos/agrovoc/c_89d3dcbb",
    "land administration" : "http://aims.fao.org/aos/agrovoc/c_9000091",
    "land area" : "http://aims.fao.org/aos/agrovoc/c_330588",
    "land clearing" : "http://aims.fao.org/aos/agrovoc/c_1662",
    "land concentration" : "http://aims.fao.org/aos/agrovoc/c_8654e90e",
    "land conflicts" : "http://aims.fao.org/aos/agrovoc/c_e236b2b1",
    "land cover mapping" : "http://aims.fao.org/aos/agrovoc/c_9000094",
    "land development (urbanization)" : "http://aims.fao.org/aos/agrovoc/c_4174",
    "land dispute" : "http://aims.fao.org/aos/agrovoc/c_1ada969a",
    "land distribution" : "http://aims.fao.org/aos/agrovoc/c_37734",
    "land environment" : "http://aims.fao.org/aos/agrovoc/c_7ffc9d69",
    "land governance" : "http://aims.fao.org/aos/agrovoc/c_aca7ac6d",
    "land grabbing" : "http://aims.fao.org/aos/agrovoc/c_cc39a497",
    "land grabs" : "http://aims.fao.org/aos/agrovoc/c_45ce1b52",
    "land information systems" : "http://aims.fao.org/aos/agrovoc/c_9000096",
    "land inheritance rights" : "http://aims.fao.org/aos/agrovoc/c_70a14ab3",
    "land investments" : "http://aims.fao.org/aos/agrovoc/c_9a4f48b4",
    "land law" : "http://aims.fao.org/aos/agrovoc/c_573abb9f",
    "land loans" : "http://aims.fao.org/aos/agrovoc/c_8b6d895f",
    "land markets" : "http://aims.fao.org/aos/agrovoc/c_4175",
    "land registration" : "http://aims.fao.org/aos/agrovoc/c_9000098",
    "land rent" : "http://aims.fao.org/aos/agrovoc/c_7bea427c",
    "land rights" : "http://aims.fao.org/aos/agrovoc/c_37898",
    "land speculation" : "http://aims.fao.org/aos/agrovoc/c_15d85712",
    "land tax" : "http://aims.fao.org/aos/agrovoc/c_4180",
    "land tenants" : "http://aims.fao.org/aos/agrovoc/c_330886",
    "land tenure systems" : "http://aims.fao.org/aos/agrovoc/c_66afb052",
    "land transfers" : "http://aims.fao.org/aos/agrovoc/c_4181",
#    "land use" : "http://aims.fao.org/aos/agrovoc/c_4182",
    "land use mapping" : "http://aims.fao.org/aos/agrovoc/c_9000100",
    "landlessness" : "http://aims.fao.org/aos/agrovoc/c_24403",
    "marital property rights" : "http://aims.fao.org/aos/agrovoc/c_64d8574a",
    "negotiated land reform" : "http://aims.fao.org/aos/agrovoc/c_f84a48c4",
    "open access (land)" : "http://aims.fao.org/aos/agrovoc/c_51a39a94",
    "pastoral land rights" : "http://aims.fao.org/aos/agrovoc/c_4d6b6100",
    "pastoral lands" : "http://aims.fao.org/aos/agrovoc/c_8e487587",
    "priest of the land" : "http://aims.fao.org/aos/agrovoc/c_28f78be5",
    "regularization of illegal occupation" : "http://aims.fao.org/aos/agrovoc/c_3b50d6b6",
    "right of first occupancy" : "http://aims.fao.org/aos/agrovoc/c_9904d265",
    "scrublands" : "http://aims.fao.org/aos/agrovoc/c_6887",
    "security of tenure (land)" : "http://aims.fao.org/aos/agrovoc/c_7fc44e33",
    "sustainable land management" : "http://aims.fao.org/aos/agrovoc/c_36580",
    "tenant farmers" : "http://aims.fao.org/aos/agrovoc/c_f73955fb",
    "title deed" : "http://aims.fao.org/aos/agrovoc/c_b769471e",
    "Torrens system" : "http://aims.fao.org/aos/agrovoc/c_7017dc39",
    "unclaimed lands" : "http://aims.fao.org/aos/agrovoc/c_0e0e555b",
    "land cover" : "http://aims.fao.org/aos/agrovoc/c_37897", 
    "land management" : "http://aims.fao.org/aos/agrovoc/c_24866",
    "land improvement" : "http://aims.fao.org/aos/agrovoc/c_28717",
###############################################################################
    "tenure" : "http://aims.fao.org/aos/agrovoc/c_7669",
    "land resources" : "http://aims.fao.org/aos/agrovoc/c_4179",
    "land ownership" : "http://aims.fao.org/aos/agrovoc/c_4184",
    "land reform" : "http://aims.fao.org/aos/agrovoc/c_4178",
    "forest land" : "http://aims.fao.org/aos/agrovoc/c_24843",
    "land economics" : "http://aims.fao.org/aos/agrovoc/c_25195",
    "property rights" : "http://aims.fao.org/aos/agrovoc/c_6192",
    "land tenure" : "http://aims.fao.org/aos/agrovoc/c_12069",
    "land suitability" : "http://aims.fao.org/aos/agrovoc/c_15992",
    "land policies" : "http://aims.fao.org/aos/agrovoc/c_195",
    "land productivity" : "http://aims.fao.org/aos/agrovoc/c_4176",
    "landowners" : "http://aims.fao.org/aos/agrovoc/c_4184",
    "land use planning" : "http://aims.fao.org/aos/agrovoc/c_37899",
    "water rights" : "http://aims.fao.org/aos/agrovoc/c_16062",
    "land diversion" : "http://aims.fao.org/aos/agrovoc/c_28716",
    "land classification" : "http://aims.fao.org/aos/agrovoc/c_15991",
    "land degradation" : "http://aims.fao.org/aos/agrovoc/c_34823",
    "land consolidation" : "http://aims.fao.org/aos/agrovoc/c_4173",
    "common lands" : "http://aims.fao.org/aos/agrovoc/c_1782",
    "grazing lands" : "http://aims.fao.org/aos/agrovoc/c_3369",
}

HARVEST_LIST_WITH_LAND = {
    "agropastoral systems" : "http://aims.fao.org/aos/agrovoc/c_16112",
    "arid zones" : "http://aims.fao.org/aos/agrovoc/c_613",
    "common property" : "http://aims.fao.org/aos/agrovoc/c_9000022",
    "commons" : "http://aims.fao.org/aos/agrovoc/c_778a14cf",
    "community forestry" : "http://aims.fao.org/aos/agrovoc/c_16532",
    "desertification" : "http://aims.fao.org/aos/agrovoc/c_2204",
    "displacement" : "http://aims.fao.org/aos/agrovoc/c_65c7772b",
    "geographical information systems" : "http://aims.fao.org/aos/agrovoc/c_35131",
    "pastoralism" : "http://aims.fao.org/aos/agrovoc/c_16144",
    "private ownership" : "http://aims.fao.org/aos/agrovoc/c_16144",
    "public ownership" : "http://aims.fao.org/aos/agrovoc/c_6350",
    "reforestation" : "http://aims.fao.org/aos/agrovoc/c_13802",
    "right of access" : "http://aims.fao.org/aos/agrovoc/c_6604",
    "urban planning" : "http://aims.fao.org/aos/agrovoc/c_37948",
    "women" : "http://aims.fao.org/aos/agrovoc/c_8420",
    "climate change" : "http://aims.fao.org/aos/agrovoc/c_1666",
    "deforestation" : "http://aims.fao.org/aos/agrovoc/c_15590",
    "food security" : "http://aims.fao.org/aos/agrovoc/c_10967",
    "rangelands" : "http://aims.fao.org/aos/agrovoc/c_6448",
    "urbanization" : "http://aims.fao.org/aos/agrovoc/c_8088",
    "water management" : "http://aims.fao.org/aos/agrovoc/c_8320",
}


#From Vittoria email 2nd september
INITIAL_HARVEST_LIST_LAREFERENCIA = ["acceso a la tierra", "areas rurales", "areas urbanas", "baldios", "bienes comunes", "cambio climatico", "conflictos por la tierra", "deforestacion", "derecho agrario", "derecho al agua", "derecho consuetudinario", "derechos a la tierra", "derecho de propiedad", "derechos indigenas", "desalojo", "desarrollo sostenible", "desarrollo urbano", "desertificacion", "desplazamiento", "desposesion", "distribucion de la tierra", "manejo forestal", "manejo de aguas", "medio ambiente", "mercados de tierras", "mineria", "mujeres rurales", "pastoreo", "politicas de tierra", "propiedad", "propiedad comunal", "propiedad de la tierra", "propiedad privada", "pueblos indigenas", "reforma agraria", "seguridad alimentaria", "sistema catastral", "tenencia de la tierra", "tierras agricolas", "tierras indigenas"]

HARVEST_LIST_LAREFERENCIA = ["acceso a la tierra", "baldios", "conflictos por la tierra", "deforestacion", "derecho al agua", "derechos a la tierra", "derecho de propiedad", "desalojo", "desertificacion", "desplazamiento", "distribucion de la tierra", "manejo forestal", "manejo de aguas", "mercados de tierras", "pastoreo", "politicas de tierra","propiedad de la tierra", "sistema catastral", "tenencia de la tierra", "tierras agricolas", "tierras indigenas", "administración catastral", "tierras comunales", "expropiación", "barrio pobre", "expansión urbana", "igualdad de género", "derechos mujeres"]

HARVEST_LIST_WITH_LAND_LAREFERENCIA = ["areas rurales", "areas urbanas", "adquisiciones", "acaparamiento", "bienes comunes", "cambio climatico", "derecho agrario", "derecho consuetudinario", "derechos indigenas", "desarrollo sostenible", "desarrollo urbano", "desposesion", "género", "inversión", "medio ambiente", "mineria", "mujeres rurales", "mujer", "mujeres", "propiedad", "propiedad comunal", "propiedad privada", "pueblos indigenas", "reforma agraria", "seguridad alimentaria", "urbanización"]
